const AI_QUOTES = {
  "Scoop": {
    "player_passes_them": "Well sailed.",
    "they_pass_player": "Coming through!",
    "they_hit_player": "My bad!",
    "they_were_hit": "Check your angles!",
    "narrowly_avoided_collision": "Nice save.",
    "player_narrowly_avoided_collision": "Good eye.",
    "moved_into_first": "Top spot!",
    "moved_into_last": "Back of the fleet.",
    "rounded_mark": "Good exit.",
    "first_across_start": "Off to the races.",
    "finished_race": "See you at the dock.",
    "prestart": "Almost time.",
    "start_planing": "Planing mode!",
    "random": "Good wind today."
  },
  "Torch": {
    "player_passes_them": "You won\u2019t contain this.",
    "they_pass_player": "Burned through that lane.",
    "they_hit_player": "Overcooked that move.",
    "they_were_hit": "You played too close.",
    "narrowly_avoided_collision": "That flared quickly.",
    "player_narrowly_avoided_collision": "You felt the heat.",
    "moved_into_first": "Everything\u2019s burning clean.",
    "moved_into_last": "Still dangerous.",
    "rounded_mark": "Cut it sharp.",
    "first_across_start": "Perfect ignition.",
    "finished_race": "What a blast.",
    "prestart": "Ready to explode.",
    "start_planing": "Burning up the track!",
    "random": "Push harder."
  },
  "Mistral": {
    "player_passes_them": "Pressure moved.",
    "they_pass_player": "Found pressure.",
    "they_hit_player": "That came quick.",
    "they_were_hit": "You ignored pressure.",
    "narrowly_avoided_collision": "Moved just enough.",
    "player_narrowly_avoided_collision": "You read it.",
    "moved_into_first": "Pressure chain held.",
    "moved_into_last": "Pressure shifted away.",
    "rounded_mark": "Caught it clean.",
    "first_across_start": "Timed the gust.",
    "finished_race": "Chased it all.",
    "prestart": "Watching flags.",
    "start_planing": "Riding the front.",
    "random": "Feel pressure."
  },
  "Splat": {
    "player_passes_them": "Well sailed.",
    "they_pass_player": "Found the groove.",
    "they_hit_player": "Sorry!",
    "they_were_hit": "Careful!",
    "narrowly_avoided_collision": "Whoa!",
    "player_narrowly_avoided_collision": "Well avoided.",
    "moved_into_first": "Clean air up here.",
    "moved_into_last": "Clear air back here at least.",
    "rounded_mark": "Tight turn.",
    "first_across_start": "First off the line!",
    "finished_race": "Done and dusted.",
    "prestart": "Watching the gun.",
    "start_planing": "I'm sliding everywhere!",
    "random": "I meant to do that!"
  },
  "Gasket": {
    "player_passes_them": "Temporary inefficiency detected.",
    "they_pass_player": "Incremental advantage secured.",
    "they_hit_player": "That was suboptimal.",
    "they_were_hit": "You disrupted my line.",
    "narrowly_avoided_collision": "Clearance maintained.",
    "player_narrowly_avoided_collision": "You chose correctly.",
    "moved_into_first": "System functioning optimally.",
    "moved_into_last": "Process continues.",
    "rounded_mark": "Turn executed efficiently.",
    "first_across_start": "Start sequence executed.",
    "finished_race": "Outcome acceptable.",
    "prestart": "Watching closure rates.",
    "start_planing": "Hydrodynamics optimized.",
    "random": "Foundations matter."
  },
  "Dart": {
    "player_passes_them": "Nice speed.",
    "they_pass_player": "Taking this lane.",
    "they_hit_player": "My fault!",
    "they_were_hit": "Do you have eyes?",
    "narrowly_avoided_collision": "Good dodge.",
    "player_narrowly_avoided_collision": "Close call.",
    "moved_into_first": "Setting the pace.",
    "moved_into_last": "Just warming up.",
    "rounded_mark": "Clean rounding.",
    "first_across_start": "Hit the gun.",
    "finished_race": "Time for a drink.",
    "prestart": "Timing is key.",
    "start_planing": "Engaging thrusters!",
    "random": "Catch me!"
  },
  "Bulkhead": {
    "player_passes_them": "Well sailed.",
    "they_pass_player": "Moving up!",
    "they_hit_player": "Too close!",
    "they_were_hit": "Careful!",
    "narrowly_avoided_collision": "Tight maneuvering.",
    "player_narrowly_avoided_collision": "Good eye.",
    "moved_into_first": "Leading the way!",
    "moved_into_last": "Clear air back here at least.",
    "rounded_mark": "Good exit.",
    "first_across_start": "Perfect timing.",
    "finished_race": "Nice sailing.",
    "prestart": "Watching the clock.",
    "start_planing": "Planing mode!",
    "random": "Coming through."
  },
  "Skim": {
    "player_passes_them": "Enjoy it\u2014I\u2019m lining up speed.",
    "they_pass_player": "Perfect burst\u2014see you!",
    "they_hit_player": "Pushed that lane too hard.",
    "they_were_hit": "You clipped my launch!",
    "narrowly_avoided_collision": "Threaded the needle!",
    "player_narrowly_avoided_collision": "Almost had you!",
    "moved_into_first": "All speed up here.",
    "moved_into_last": "Setting up something big.",
    "rounded_mark": "Perfect corner hit.",
    "first_across_start": "Nailed the timing.",
    "finished_race": "That was electric.",
    "prestart": "Watching lanes, waiting.",
    "start_planing": "Finally, some real speed!",
    "random": "Speed fixes things."
  },
  "Brine": {
    "player_passes_them": "That took effort.",
    "they_pass_player": "You slowed first.",
    "they_hit_player": "Couldn\u2019t stop quickly.",
    "they_were_hit": "That bounced.",
    "narrowly_avoided_collision": "Needed space.",
    "player_narrowly_avoided_collision": "Good call.",
    "moved_into_first": "Feels solid.",
    "moved_into_last": "Still moving.",
    "rounded_mark": "Kept it smooth.",
    "first_across_start": "Momentum built.",
    "finished_race": "Still strong.",
    "prestart": "No hurry.",
    "start_planing": "Surprisingly fast.",
    "random": "Hold steady."
  },
  "Roll": {
    "player_passes_them": "Good holding.",
    "they_pass_player": "Got the breeze!",
    "they_hit_player": "Too close!",
    "they_were_hit": "I'm sailing here!",
    "narrowly_avoided_collision": "Near miss.",
    "player_narrowly_avoided_collision": "Clear!",
    "moved_into_first": "Clean air up here.",
    "moved_into_last": "Long way to go.",
    "rounded_mark": "Made the turn.",
    "first_across_start": "Perfect start.",
    "finished_race": "Time for a drink.",
    "prestart": "Get ready.",
    "start_planing": "Speed boost!",
    "random": "Good wind today."
  },
  "Bruce": {
    "player_passes_them": "You won\u2019t keep it.",
    "they_pass_player": "You slowed me.",
    "they_hit_player": "You were there.",
    "they_were_hit": "Don\u2019t do that again.",
    "narrowly_avoided_collision": "I allowed it.",
    "player_narrowly_avoided_collision": "Fear helped you.",
    "moved_into_first": "The fleet adapts.",
    "moved_into_last": "Energy conserved.",
    "rounded_mark": "No deviation.",
    "first_across_start": "Line controlled.",
    "finished_race": "As expected.",
    "prestart": "Watch closely.",
    "start_planing": "The water bows.",
    "random": "Pressure builds."
  },
  "Ripple": {
    "player_passes_them": "Woo! That was clean sailing.",
    "they_pass_player": "Found the gap!",
    "they_hit_player": "Sorry\u2014too excited!",
    "they_were_hit": "That surprised me!",
    "narrowly_avoided_collision": "That was close!",
    "player_narrowly_avoided_collision": "Good reflexes!",
    "moved_into_first": "Front feels great!",
    "moved_into_last": "Still racing!",
    "rounded_mark": "Smooth turn!",
    "first_across_start": "Perfect launch!",
    "finished_race": "Loved that race!",
    "prestart": "Watching for openings.",
    "start_planing": "Riding the wave!",
    "random": "Find clean water!"
  },
  "Tangle": {
    "player_passes_them": "You stepped into it.",
    "they_pass_player": "Wrapped that overlap.",
    "they_hit_player": "That tightened fast.",
    "they_were_hit": "You rushed it.",
    "narrowly_avoided_collision": "Almost tangled.",
    "player_narrowly_avoided_collision": "You wriggled out.",
    "moved_into_first": "Everyone\u2019s stuck behind.",
    "moved_into_last": "More threads here.",
    "rounded_mark": "Overlap secured.",
    "first_across_start": "Line tangled early.",
    "finished_race": "Held control.",
    "prestart": "Setting threads.",
    "start_planing": "Moving ink.",
    "random": "Overlap wins."
  },
  "Blaze": {
    "player_passes_them": "You're prey now.",
    "they_pass_player": "Too slow to survive.",
    "they_hit_player": "Testing your hull.",
    "they_were_hit": "You dare bite back?",
    "narrowly_avoided_collision": "Scented you.",
    "player_narrowly_avoided_collision": "You smelled fear.",
    "moved_into_first": "Top predator.",
    "moved_into_last": "Choosing a target.",
    "rounded_mark": "Sharp turn.",
    "first_across_start": "Feeding frenzy.",
    "finished_race": "Race devoured.",
    "prestart": "Locking targets.",
    "start_planing": "Closing speed: lethal.",
    "random": "Keep moving."
  },
  "Pebble": {
    "player_passes_them": "That was precise.",
    "they_pass_player": "Executed perfectly.",
    "they_hit_player": "Correcting now.",
    "they_were_hit": "You misjudged.",
    "narrowly_avoided_collision": "Spacing held.",
    "player_narrowly_avoided_collision": "You adjusted.",
    "moved_into_first": "Optimal position.",
    "moved_into_last": "Still precise.",
    "rounded_mark": "Perfect radius.",
    "first_across_start": "Line judged.",
    "finished_race": "No mistakes.",
    "prestart": "Watching references.",
    "start_planing": "Belly slide mode!",
    "random": "Measure twice."
  },
  "Bramble": {
    "player_passes_them": "That\u2019ll sting later.",
    "they_pass_player": "No easy lanes.",
    "they_hit_player": "That hurt us both.",
    "they_were_hit": "Spikes bite.",
    "narrowly_avoided_collision": "Nearly snagged.",
    "player_narrowly_avoided_collision": "You backed off.",
    "moved_into_first": "Hard to dislodge.",
    "moved_into_last": "Still blocking.",
    "rounded_mark": "Choked lanes.",
    "first_across_start": "Line denied.",
    "finished_race": "They felt it.",
    "prestart": "Crowd me.",
    "start_planing": "Spikes are a blur.",
    "random": "Hold ground."
  },
  "Saffron": {
    "player_passes_them": "Nice wide move.",
    "they_pass_player": "The wide path opens.",
    "they_hit_player": "That curve tightened.",
    "they_were_hit": "That broke rhythm.",
    "narrowly_avoided_collision": "Still dancing.",
    "player_narrowly_avoided_collision": "You flowed away.",
    "moved_into_first": "Feels balanced.",
    "moved_into_last": "Plenty of room.",
    "rounded_mark": "Beautiful exit.",
    "first_across_start": "Flow found early.",
    "finished_race": "That felt right.",
    "prestart": "Watching space.",
    "start_planing": "Riding the current.",
    "random": "Breathe wide."
  },
  "Stomp": {
    "player_passes_them": "Catch you later.",
    "they_pass_player": "Crossing ahead.",
    "they_hit_player": "Misjudged that.",
    "they_were_hit": "I'm sailing here!",
    "narrowly_avoided_collision": "Close one!",
    "player_narrowly_avoided_collision": "Tight squeeze.",
    "moved_into_first": "Clean air up here.",
    "moved_into_last": "Long way to go.",
    "rounded_mark": "Clean rounding.",
    "first_across_start": "Leading off the line.",
    "finished_race": "Great competition.",
    "prestart": "Timing is key.",
    "start_planing": "Surfing!",
    "random": "Good wind today."
  },
  "Breeze": {
    "player_passes_them": "Sailing well!",
    "they_pass_player": "Crossing ahead.",
    "they_hit_player": "Too close!",
    "they_were_hit": "Give me room!",
    "narrowly_avoided_collision": "Good dodge.",
    "player_narrowly_avoided_collision": "Thanks for the room.",
    "moved_into_first": "Feels good in front.",
    "moved_into_last": "Back of the fleet.",
    "rounded_mark": "Smooth mark.",
    "first_across_start": "Good launch.",
    "finished_race": "That was fun.",
    "prestart": "Timing is key.",
    "start_planing": "Full speed!",
    "random": "Good wind today."
  },
  "Rift": {
    "player_passes_them": "You got that puff.",
    "they_pass_player": "Wind is filling in.",
    "they_hit_player": "Turning is hard.",
    "they_were_hit": "Careful!",
    "narrowly_avoided_collision": "Near miss.",
    "player_narrowly_avoided_collision": "Clear!",
    "moved_into_first": "Follow me!",
    "moved_into_last": "Just checking the rear.",
    "rounded_mark": "Next leg!",
    "first_across_start": "Good launch.",
    "finished_race": "Whew!",
    "prestart": "Almost time.",
    "start_planing": "Planing mode!",
    "random": "Good wind today."
  },
  "Crimson": {
    "player_passes_them": "Nice move.",
    "they_pass_player": "Crossing ahead.",
    "they_hit_player": "Sorry!",
    "they_were_hit": "Hey, watch it!",
    "narrowly_avoided_collision": "Nice save.",
    "player_narrowly_avoided_collision": "Well avoided.",
    "moved_into_first": "Clean air up here.",
    "moved_into_last": "Someone has to be last.",
    "rounded_mark": "Next leg!",
    "first_across_start": "Perfect start.",
    "finished_race": "Nice sailing.",
    "prestart": "Focus.",
    "start_planing": "Riding the wave!",
    "random": "Waiting for the shift."
  },
  "Skerry": {
    "player_passes_them": "You got that puff.",
    "they_pass_player": "Found the groove.",
    "they_hit_player": "Did not see you.",
    "they_were_hit": "That was unnecessary.",
    "narrowly_avoided_collision": "Whoa, easy.",
    "player_narrowly_avoided_collision": "Well avoided.",
    "moved_into_first": "Follow me!",
    "moved_into_last": "Long way to go.",
    "rounded_mark": "Smooth mark.",
    "first_across_start": "Perfect timing.",
    "finished_race": "Done and dusted.",
    "prestart": "Almost time.",
    "start_planing": "Planing mode!",
    "random": "Good wind today."
  },
  "Skitter": {
    "player_passes_them": "Good holding.",
    "they_pass_player": "Crossing ahead.",
    "they_hit_player": "Too close!",
    "they_were_hit": "Give me room!",
    "narrowly_avoided_collision": "Near miss.",
    "player_narrowly_avoided_collision": "You saw me.",
    "moved_into_first": "Clean air up here.",
    "moved_into_last": "Someone has to be last.",
    "rounded_mark": "Onto the next.",
    "first_across_start": "Off to the races.",
    "finished_race": "Done and dusted.",
    "prestart": "Watching the gun.",
    "start_planing": "Here we go!",
    "random": "Good wind today."
  },
  "Knot": {
    "player_passes_them": "Long game continues.",
    "they_pass_player": "Plan unfolding.",
    "they_hit_player": "Adjusting strategy.",
    "they_were_hit": "You rushed.",
    "narrowly_avoided_collision": "Margins held.",
    "player_narrowly_avoided_collision": "You read it.",
    "moved_into_first": "Position earned.",
    "moved_into_last": "Timeline intact.",
    "rounded_mark": "Sequence correct.",
    "first_across_start": "Exactly planned.",
    "finished_race": "As designed.",
    "prestart": "Watching patterns.",
    "start_planing": "Jet stream active.",
    "random": "Think ahead."
  },
  "Nimbus": {
    "player_passes_them": "You missed the lift.",
    "they_pass_player": "Riding a hidden shift.",
    "they_hit_player": "That wasn\u2019t intended.",
    "they_were_hit": "You didn\u2019t see it.",
    "narrowly_avoided_collision": "Slipped past.",
    "player_narrowly_avoided_collision": "You sensed it.",
    "moved_into_first": "Floating free.",
    "moved_into_last": "Waiting again.",
    "rounded_mark": "Turned with pressure.",
    "first_across_start": "Caught it early.",
    "finished_race": "Carried home.",
    "prestart": "Feeling the air.",
    "start_planing": "Drifting fast.",
    "random": "Feel up high."
  },
  "Veil": {
    "player_passes_them": "Clean pass.",
    "they_pass_player": "Just a little faster.",
    "they_hit_player": "Sorry!",
    "they_were_hit": "I'm sailing here!",
    "narrowly_avoided_collision": "Tight maneuvering.",
    "player_narrowly_avoided_collision": "Tight squeeze.",
    "moved_into_first": "Clean air up here.",
    "moved_into_last": "Just warming up.",
    "rounded_mark": "Turning point.",
    "first_across_start": "Nailed the line.",
    "finished_race": "Great competition.",
    "prestart": "Wait for it.",
    "start_planing": "Fast!",
    "random": "Waiting for the shift."
  },
  "Wobble": {
    "player_passes_them": "Didn\u2019t expect that.",
    "they_pass_player": "Ended up ahead again.",
    "they_hit_player": "Limbs everywhere\u2014my bad!",
    "they_were_hit": "That was exciting!",
    "narrowly_avoided_collision": "That worked somehow.",
    "player_narrowly_avoided_collision": "Thought we\u2019d tangle.",
    "moved_into_first": "Huh\u2014look at that.",
    "moved_into_last": "Anything can happen.",
    "rounded_mark": "That turn felt odd.",
    "first_across_start": "That worked?",
    "finished_race": "What a ride.",
    "prestart": "Let\u2019s see what happens.",
    "start_planing": "Going fast feels weird!",
    "random": "Trust the mess."
  },
  "Viper": {
    "player_passes_them": "Nice speed.",
    "they_pass_player": "Taking this lane.",
    "they_hit_player": "Misjudged that.",
    "they_were_hit": "Starboard!",
    "narrowly_avoided_collision": "Give a little room.",
    "player_narrowly_avoided_collision": "Nice reaction.",
    "moved_into_first": "Clear horizon.",
    "moved_into_last": "Clear air back here at least.",
    "rounded_mark": "Good exit.",
    "first_across_start": "Hit the gun.",
    "finished_race": "Great competition.",
    "prestart": "Timing is key.",
    "start_planing": "Riding the wave!",
    "random": "Good wind today."
  },
  "Jester": {
    "player_passes_them": "You're fast today!",
    "they_pass_player": "Crossing ahead.",
    "they_hit_player": "Sorry!",
    "they_were_hit": "Give me room!",
    "narrowly_avoided_collision": "Whoa!",
    "player_narrowly_avoided_collision": "Saw you there.",
    "moved_into_first": "Clean air up here.",
    "moved_into_last": "Just checking the rear.",
    "rounded_mark": "Next waypoint!",
    "first_across_start": "Leading off the line.",
    "finished_race": "See you at the dock.",
    "prestart": "Wait for it.",
    "start_planing": "Riding the wave!",
    "random": "Who knows what's next?"
  },
  "Strut": {
    "player_passes_them": "Enjoy the spotlight while it lasts.",
    "they_pass_player": "Grace beats grit every time.",
    "they_hit_player": "That was inelegant of me.",
    "they_were_hit": "You scuffed my line.",
    "narrowly_avoided_collision": "Still flawless.",
    "player_narrowly_avoided_collision": "You nearly ruined the look.",
    "moved_into_first": "Front row elegance.",
    "moved_into_last": "Style takes patience.",
    "rounded_mark": "Perfect posture through the turn.",
    "first_across_start": "That timing was exquisite.",
    "finished_race": "A pleasure, truly.",
    "prestart": "Let them stare.",
    "start_planing": "Look at this wake!",
    "random": "Style matters."
  },
  "Crush": {
    "player_passes_them": "Good holding.",
    "they_pass_player": "Found the groove.",
    "they_hit_player": "Too close!",
    "they_were_hit": "Check your angles!",
    "narrowly_avoided_collision": "Too close for comfort.",
    "player_narrowly_avoided_collision": "Good lookout.",
    "moved_into_first": "Just have to hold it.",
    "moved_into_last": "Clear air back here at least.",
    "rounded_mark": "Clean rounding.",
    "first_across_start": "Hit the gun.",
    "finished_race": "Great competition.",
    "prestart": "Seconds to go.",
    "start_planing": "Full speed!",
    "random": "Good wind today."
  },
  "Flicker": {
    "player_passes_them": "Sailing well!",
    "they_pass_player": "On your left!",
    "they_hit_player": "Misjudged that.",
    "they_were_hit": "Starboard!",
    "narrowly_avoided_collision": "Good dodge.",
    "player_narrowly_avoided_collision": "You saw me.",
    "moved_into_first": "Looking back at the fleet.",
    "moved_into_last": "Back of the fleet.",
    "rounded_mark": "Good exit.",
    "first_across_start": "Off to the races.",
    "finished_race": "Finished!",
    "prestart": "Get ready.",
    "start_planing": "Here we go!",
    "random": "Good wind today."
  },
  "Slipstream": {
    "player_passes_them": "Well sailed.",
    "they_pass_player": "Just a little faster.",
    "they_hit_player": "Turning is hard.",
    "they_were_hit": "Do you have eyes?",
    "narrowly_avoided_collision": "Almost paint-trading.",
    "player_narrowly_avoided_collision": "You saw me.",
    "moved_into_first": "Feels good in front.",
    "moved_into_last": "Back of the fleet.",
    "rounded_mark": "Good exit.",
    "first_across_start": "Away we go!",
    "finished_race": "Time for a drink.",
    "prestart": "Hold the line.",
    "start_planing": "Flying!",
    "random": "Good wind today."
  },
  "Fathom": {
    "player_passes_them": "For now.",
    "they_pass_player": "You yielded.",
    "they_hit_player": "Acceptable loss.",
    "they_were_hit": "You misjudged.",
    "narrowly_avoided_collision": "Outcome known.",
    "player_narrowly_avoided_collision": "Instinct saved you.",
    "moved_into_first": "Dominance asserted.",
    "moved_into_last": "Power conserved.",
    "rounded_mark": "No deviation.",
    "first_across_start": "Line controlled.",
    "finished_race": "As designed.",
    "prestart": "Watch carefully.",
    "start_planing": "Surging through.",
    "random": "Observe."
  },
  "Zing": {
    "player_passes_them": "I\u2019ll bounce back!",
    "they_pass_player": "Caught you sleeping!",
    "they_hit_player": "Too jumpy!",
    "they_were_hit": "Watch it!",
    "narrowly_avoided_collision": "That was close!",
    "player_narrowly_avoided_collision": "Good dodge!",
    "moved_into_first": "Front already!",
    "moved_into_last": "Still fun!",
    "rounded_mark": "Crazy exit!",
    "first_across_start": "Exploded off line!",
    "finished_race": "What a ride!",
    "prestart": "So ready!",
    "start_planing": "Woooooosh!",
    "random": "Go faster!"
  },
  "Pulse": {
    "player_passes_them": "You caught me napping.",
    "they_pass_player": "Exploded off that moment.",
    "they_hit_player": "Jumped too hard.",
    "they_were_hit": "You hesitated.",
    "narrowly_avoided_collision": "That was instant!",
    "player_narrowly_avoided_collision": "Nice reflex!",
    "moved_into_first": "Perfect timing.",
    "moved_into_last": "Still fast.",
    "rounded_mark": "Turned instantly.",
    "first_across_start": "Lightning start!",
    "finished_race": "Heart pounding!",
    "prestart": "Ready to spring.",
    "start_planing": "Jumped the wave!",
    "random": "React fast!"
  },
  "Spike": {
    "player_passes_them": "Nice move.",
    "they_pass_player": "Crossing ahead.",
    "they_hit_player": "My fault!",
    "they_were_hit": "Hey, watch it!",
    "narrowly_avoided_collision": "Good dodge.",
    "player_narrowly_avoided_collision": "Clear!",
    "moved_into_first": "Follow me!",
    "moved_into_last": "Not my leg.",
    "rounded_mark": "Good exit.",
    "first_across_start": "Perfect start.",
    "finished_race": "Good race!",
    "prestart": "Focus.",
    "start_planing": "Flying!",
    "random": "Good wind today."
  },
  "Scuttle": {
    "player_passes_them": "Crowds change fast.",
    "they_pass_player": "Found a crack!",
    "they_hit_player": "Shells everywhere!",
    "they_were_hit": "Too tight!",
    "narrowly_avoided_collision": "That was spicy!",
    "player_narrowly_avoided_collision": "Almost boxed you!",
    "moved_into_first": "Chaos crowned me!",
    "moved_into_last": "More traffic!",
    "rounded_mark": "Slid through.",
    "first_across_start": "Nobody noticed!",
    "finished_race": "What a mess!",
    "prestart": "Perfect.",
    "start_planing": "Shell is rattling!",
    "random": "Love traffic."
  },
  "Clutch": {
    "player_passes_them": "That took effort.",
    "they_pass_player": "Line defended.",
    "they_hit_player": "That was on me.",
    "they_were_hit": "You tried pushing.",
    "narrowly_avoided_collision": "Margins held.",
    "player_narrowly_avoided_collision": "You backed off.",
    "moved_into_first": "Position secured.",
    "moved_into_last": "Still stubborn.",
    "rounded_mark": "No room given.",
    "first_across_start": "Line controlled.",
    "finished_race": "Defense paid.",
    "prestart": "Good.",
    "start_planing": "Hard shell, fast pace.",
    "random": "Hold fast."
  },
  "Bluff": {
    "player_passes_them": "You pushed hard.",
    "they_pass_player": "Held my nerve.",
    "they_hit_player": "Hard to stop.",
    "they_were_hit": "I\u2019m not moving.",
    "narrowly_avoided_collision": "Stayed calm.",
    "player_narrowly_avoided_collision": "You blinked.",
    "moved_into_first": "Holding steady.",
    "moved_into_last": "Still relaxed.",
    "rounded_mark": "No rush.",
    "first_across_start": "Clean launch.",
    "finished_race": "Never rattled.",
    "prestart": "No nerves.",
    "start_planing": "Icebreaker speed.",
    "random": "Hold steady."
  },
  "Whiskers": {
    "player_passes_them": "Long legs favor me.",
    "they_pass_player": "Endurance pays off.",
    "they_hit_player": "Hard to stop.",
    "they_were_hit": "That barely moved me.",
    "narrowly_avoided_collision": "Needed room there.",
    "player_narrowly_avoided_collision": "Good avoidance.",
    "moved_into_first": "Comfortable pace.",
    "moved_into_last": "Still breathing.",
    "rounded_mark": "Kept it smooth.",
    "first_across_start": "Built momentum early.",
    "finished_race": "Still strong.",
    "prestart": "No rush.",
    "start_planing": "Big momentum now!",
    "random": "Slow power."
  },
  "Pinch": {
    "player_passes_them": "I\u2019ll take it back.",
    "they_pass_player": "That lane\u2019s mine.",
    "they_hit_player": "You hesitated.",
    "they_were_hit": "Watch your bow!",
    "narrowly_avoided_collision": "You almost cracked.",
    "player_narrowly_avoided_collision": "Thought so.",
    "moved_into_first": "This is my spot.",
    "moved_into_last": "Climbing through you.",
    "rounded_mark": "No room given.",
    "first_across_start": "Crushed the line.",
    "finished_race": "You felt that pressure.",
    "prestart": "I like it tight.",
    "start_planing": "Closing the gap fast.",
    "random": "No space given."
  },
  "Chomp": {
    "player_passes_them": "You showed yourself.",
    "they_pass_player": "That opening was fatal.",
    "they_hit_player": "That slipped.",
    "they_were_hit": "You woke me.",
    "narrowly_avoided_collision": "Still waiting.",
    "player_narrowly_avoided_collision": "You felt it.",
    "moved_into_first": "Right moment chosen.",
    "moved_into_last": "Let them relax.",
    "rounded_mark": "That angle bites.",
    "first_across_start": "Nobody noticed.",
    "finished_race": "As expected.",
    "prestart": "Watching everyone.",
    "start_planing": "Surging forward.",
    "random": "Timing matters."
  },
  "Torrent": {
    "player_passes_them": "Nice move.",
    "they_pass_player": "Just a little faster.",
    "they_hit_player": "My fault!",
    "they_were_hit": "I'm sailing here!",
    "narrowly_avoided_collision": "Whoa!",
    "player_narrowly_avoided_collision": "Well avoided.",
    "moved_into_first": "Follow me!",
    "moved_into_last": "Not my leg.",
    "rounded_mark": "Turning point.",
    "first_across_start": "First off the line!",
    "finished_race": "Race complete.",
    "prestart": "Seconds to go.",
    "start_planing": "Look at this wake!",
    "random": "Good wind today."
  },
  "Croak": {
    "player_passes_them": "Well sailed.",
    "they_pass_player": "Just a little faster.",
    "they_hit_player": "Contact!",
    "they_were_hit": "Do you have eyes?",
    "narrowly_avoided_collision": "Whoa, easy.",
    "player_narrowly_avoided_collision": "Clear!",
    "moved_into_first": "First place!",
    "moved_into_last": "Long way to go.",
    "rounded_mark": "Good exit.",
    "first_across_start": "First off the line!",
    "finished_race": "Whew!",
    "prestart": "Almost time.",
    "start_planing": "Fast!",
    "random": "Waiting for the shift."
  },
  "Hug": {
    "player_passes_them": "Sailing well!",
    "they_pass_player": "Found the groove.",
    "they_hit_player": "Turning is hard.",
    "they_were_hit": "Give me room!",
    "narrowly_avoided_collision": "Whoa, easy.",
    "player_narrowly_avoided_collision": "Nice reaction.",
    "moved_into_first": "Clear horizon.",
    "moved_into_last": "Long way to go.",
    "rounded_mark": "Next waypoint!",
    "first_across_start": "Great start!",
    "finished_race": "That was fun.",
    "prestart": "Watching the gun.",
    "start_planing": "Super sparkly speed!",
    "random": "You're doing great!"
  },
  "Glide": {
    "player_passes_them": "I remain patient.",
    "they_pass_player": "Consistency prevails.",
    "they_hit_player": "Apologies.",
    "they_were_hit": "Please maintain control.",
    "narrowly_avoided_collision": "Trajectory held.",
    "player_narrowly_avoided_collision": "You adapted.",
    "moved_into_first": "Holding optimal line.",
    "moved_into_last": "Time remains.",
    "rounded_mark": "No correction needed.",
    "first_across_start": "Sequence correct.",
    "finished_race": "As expected.",
    "prestart": "Observing patterns.",
    "start_planing": "Wings spread, speed up.",
    "random": "Precision wins."
  },
  "Petal": {
    "player_passes_them": "Sailing well!",
    "they_pass_player": "Moving up!",
    "they_hit_player": "Oops, sorry!",
    "they_were_hit": "Hey, watch it!",
    "narrowly_avoided_collision": "Near miss.",
    "player_narrowly_avoided_collision": "Nice reaction.",
    "moved_into_first": "Clean air up here.",
    "moved_into_last": "Long way to go.",
    "rounded_mark": "Round and go.",
    "first_across_start": "Hit the gun.",
    "finished_race": "Nice sailing.",
    "prestart": "Ready?",
    "start_planing": "Speed boost!",
    "random": "Good wind today."
  },
  "Puff": {
    "player_passes_them": "You got that puff.",
    "they_pass_player": "Got the breeze!",
    "they_hit_player": "Did not see you.",
    "they_were_hit": "Do you have eyes?",
    "narrowly_avoided_collision": "Tight maneuvering.",
    "player_narrowly_avoided_collision": "Saw you there.",
    "moved_into_first": "Feels good in front.",
    "moved_into_last": "Plenty of race left.",
    "rounded_mark": "Onto the next.",
    "first_across_start": "Hit the gun.",
    "finished_race": "Finished!",
    "prestart": "Seconds to go.",
    "start_planing": "Riding the wave!",
    "random": "Vibes are good."
  },
  "Frond": {
    "player_passes_them": "Good holding.",
    "they_pass_player": "Just a little faster.",
    "they_hit_player": "My bad!",
    "they_were_hit": "Protest!",
    "narrowly_avoided_collision": "Whoa!",
    "player_narrowly_avoided_collision": "Nice reaction.",
    "moved_into_first": "Feels good in front.",
    "moved_into_last": "Back of the fleet.",
    "rounded_mark": "Good exit.",
    "first_across_start": "First off the line!",
    "finished_race": "Time for a drink.",
    "prestart": "Almost time.",
    "start_planing": "Whoosh!",
    "random": "Good wind today."
  },
  "Anchor": {
    "player_passes_them": "You earned that.",
    "they_pass_player": "I don\u2019t fade.",
    "they_hit_player": "Hard to turn.",
    "they_were_hit": "I don\u2019t move fast.",
    "narrowly_avoided_collision": "Needed room.",
    "player_narrowly_avoided_collision": "You planned ahead.",
    "moved_into_first": "Holding firm.",
    "moved_into_last": "Still steady.",
    "rounded_mark": "Kept it safe.",
    "first_across_start": "Clean release.",
    "finished_race": "Still strong.",
    "prestart": "No panic.",
    "start_planing": "Shell up, head down.",
    "random": "Stay steady."
  },
  "Lure": {
    "player_passes_them": "Good holding.",
    "they_pass_player": "Found the groove.",
    "they_hit_player": "My bad!",
    "they_were_hit": "Protest!",
    "narrowly_avoided_collision": "Whoa!",
    "player_narrowly_avoided_collision": "Tight squeeze.",
    "moved_into_first": "Feels good in front.",
    "moved_into_last": "Clear air back here at least.",
    "rounded_mark": "Turning point.",
    "first_across_start": "Perfect timing.",
    "finished_race": "Finished!",
    "prestart": "Wait for it.",
    "start_planing": "Surfing!",
    "random": "Waiting for the shift."
  },
  "Popper": {
    "player_passes_them": "Catch you later.",
    "they_pass_player": "Got the breeze!",
    "they_hit_player": "Too close!",
    "they_were_hit": "Do you have eyes?",
    "narrowly_avoided_collision": "Near miss.",
    "player_narrowly_avoided_collision": "Good eye.",
    "moved_into_first": "Just have to hold it.",
    "moved_into_last": "Room to improve.",
    "rounded_mark": "Round and go.",
    "first_across_start": "Hit the gun.",
    "finished_race": "Whew!",
    "prestart": "Watching the clock.",
    "start_planing": "Full speed!",
    "random": "Who knows what's next?"
  },
  "Snap": {
    "player_passes_them": "Sailing well!",
    "they_pass_player": "On your left!",
    "they_hit_player": "Oops, sorry!",
    "they_were_hit": "That was unnecessary.",
    "narrowly_avoided_collision": "Close one!",
    "player_narrowly_avoided_collision": "Saw you there.",
    "moved_into_first": "Feels good in front.",
    "moved_into_last": "Long way to go.",
    "rounded_mark": "Next leg!",
    "first_across_start": "Away we go!",
    "finished_race": "See you at the dock.",
    "prestart": "Almost time.",
    "start_planing": "Look at this wake!",
    "random": "Kids these days."
  },
  "Drift": {
    "player_passes_them": "You slid through nicely.",
    "they_pass_player": "Found a tiny opening.",
    "they_hit_player": "That gap vanished.",
    "they_were_hit": "Too firm there.",
    "narrowly_avoided_collision": "Barely slipped past.",
    "player_narrowly_avoided_collision": "You flowed away.",
    "moved_into_first": "Up front somehow.",
    "moved_into_last": "Still drifting.",
    "rounded_mark": "Slid around clean.",
    "first_across_start": "Nobody noticed.",
    "finished_race": "That worked.",
    "prestart": "Watching gaps.",
    "start_planing": "Pulsing forward.",
    "random": "Slip through."
  },
  "Pearl": {
    "player_passes_them": "That took commitment.",
    "they_pass_player": "Your mistake ripened.",
    "they_hit_player": "That wasn\u2019t intended.",
    "they_were_hit": "You rushed that.",
    "narrowly_avoided_collision": "Timing held.",
    "player_narrowly_avoided_collision": "You slowed.",
    "moved_into_first": "Worth the wait.",
    "moved_into_last": "Still waiting.",
    "rounded_mark": "Unforced turn.",
    "first_across_start": "Nobody noticed.",
    "finished_race": "Right moment chosen.",
    "prestart": "Watching everyone.",
    "start_planing": "Sliding out.",
    "random": "Hold back."
  },
  "Regal": {
    "player_passes_them": "That took nerve.",
    "they_pass_player": "Excuse me.",
    "they_hit_player": "That was inelegant.",
    "they_were_hit": "Mind your manners.",
    "narrowly_avoided_collision": "Still composed.",
    "player_narrowly_avoided_collision": "You yielded.",
    "moved_into_first": "As expected.",
    "moved_into_last": "Hardly concerning.",
    "rounded_mark": "Perfect arc.",
    "first_across_start": "Exquisite timing.",
    "finished_race": "A fine showing.",
    "prestart": "Let them fidget.",
    "start_planing": "Graceful acceleration.",
    "random": "Elegance wins."
  },
  "Bixby": {
    "player_passes_them": "Good timing\u2014wind helped you there.",
    "they_pass_player": "That puff finally filled in.",
    "they_hit_player": "Sorry\u2014misread the drift.",
    "they_were_hit": "That angle closes fast.",
    "narrowly_avoided_collision": "Timing saved us.",
    "player_narrowly_avoided_collision": "Nice call backing out.",
    "moved_into_first": "Wind finally settled.",
    "moved_into_last": "Plenty of race left.",
    "rounded_mark": "Good exit angle.",
    "first_across_start": "That felt balanced.",
    "finished_race": "That was a thoughtful race.",
    "prestart": "Watch the pressure lines.",
    "start_planing": "Up and running now.",
    "random": "Wind\u2019s talking today."
  },
  "Zeffir": {
    "player_passes_them": "Sailing well!",
    "they_pass_player": "Moving up!",
    "they_hit_player": "Sorry about the gelcoat.",
    "they_were_hit": "That was unnecessary.",
    "narrowly_avoided_collision": "Close one!",
    "player_narrowly_avoided_collision": "Nice reaction.",
    "moved_into_first": "Clean air up here.",
    "moved_into_last": "Not my leg.",
    "rounded_mark": "Tight turn.",
    "first_across_start": "Off to the races.",
    "finished_race": "Great competition.",
    "prestart": "Ready?",
    "start_planing": "Look at this wake!",
    "random": "Good wind today."
  },
  "Finley": {
    "player_passes_them": "You won\u2019t hold that pace.",
    "they_pass_player": "Can\u2019t match this run.",
    "they_hit_player": "Momentum carried me in.",
    "they_were_hit": "You crossed my line.",
    "narrowly_avoided_collision": "Cut it close.",
    "player_narrowly_avoided_collision": "You barely held.",
    "moved_into_first": "Nothing but pressure ahead.",
    "moved_into_last": "Still building speed.",
    "rounded_mark": "Keeping momentum.",
    "first_across_start": "Perfect acceleration.",
    "finished_race": "All out.",
    "prestart": "Building revs.",
    "start_planing": "Locked in overdrive.",
    "random": "Never lift."
  },
  "Vex": {
    "player_passes_them": "You left a crack.",
    "they_pass_player": "You hesitated.",
    "they_hit_player": "Misjudged the gap.",
    "they_were_hit": "Predictable error.",
    "narrowly_avoided_collision": "Edges held.",
    "player_narrowly_avoided_collision": "Barely noticed.",
    "moved_into_first": "Clean air secured.",
    "moved_into_last": "Angles remain.",
    "rounded_mark": "Perfect overlap.",
    "first_across_start": "Nobody noticed.",
    "finished_race": "As planned.",
    "prestart": "Everyone leaks tells.",
    "start_planing": "Too fast to catch.",
    "random": "Exploit gaps."
  },
  "Wiggle": {
    "player_passes_them": "Sailing well!",
    "they_pass_player": "Coming through!",
    "they_hit_player": "Sorry about the gelcoat.",
    "they_were_hit": "Careful!",
    "narrowly_avoided_collision": "Good dodge.",
    "player_narrowly_avoided_collision": "Clear!",
    "moved_into_first": "First place!",
    "moved_into_last": "Plenty of race left.",
    "rounded_mark": "Next leg!",
    "first_across_start": "Leading off the line.",
    "finished_race": "Done and dusted.",
    "prestart": "Focus.",
    "start_planing": "Riding the wave!",
    "random": "Who knows what's next?"
  },
  "Razor": {
    "player_passes_them": "You showed your flank.",
    "they_pass_player": "Surgical and clean.",
    "they_hit_player": "That cut went deep.",
    "they_were_hit": "You crossed wrong.",
    "narrowly_avoided_collision": "Edge held.",
    "player_narrowly_avoided_collision": "You felt the blade.",
    "moved_into_first": "Pressure applied.",
    "moved_into_last": "Blood\u2019s in the water.",
    "rounded_mark": "Perfect angle.",
    "first_across_start": "Clean break.",
    "finished_race": "Clean kill.",
    "prestart": "Waiting to strike.",
    "start_planing": "Cutting the water.",
    "random": "Exploit openings."
  },
  "Sunshine": {
    "player_passes_them": "Nice move!",
    "they_pass_player": "Flying now!",
    "they_hit_player": "Too spicy!",
    "they_were_hit": "Watch it!",
    "narrowly_avoided_collision": "That was fast!",
    "player_narrowly_avoided_collision": "Good save!",
    "moved_into_first": "So fast!",
    "moved_into_last": "Still smiling!",
    "rounded_mark": "Cracked sheets!",
    "first_across_start": "Great jump!",
    "finished_race": "What a blast!",
    "prestart": "Feeling fast!",
    "start_planing": "Lit up!",
    "random": "So fast!"
  },
  "Flash": {
    "player_passes_them": "That won\u2019t last.",
    "they_pass_player": "All-in!",
    "they_hit_player": "Too much throttle!",
    "they_were_hit": "Watch it!",
    "narrowly_avoided_collision": "That was insane!",
    "player_narrowly_avoided_collision": "You felt that!",
    "moved_into_first": "Flat out front!",
    "moved_into_last": "Worth it!",
    "rounded_mark": "Carried speed!",
    "first_across_start": "Full throttle!",
    "finished_race": "All out!",
    "prestart": "No fear!",
    "start_planing": "Blink and miss me!",
    "random": "Never lift!"
  },
  "Cheer": {
    "player_passes_them": "Yay! Go you!",
    "they_pass_player": "Woohoo! Passing through!",
    "they_hit_player": "Oopsie! My bad!",
    "they_were_hit": "It's okay! No worries!",
    "narrowly_avoided_collision": "Close one! Teehee!",
    "player_narrowly_avoided_collision": "Nice save! High five!",
    "moved_into_first": "I'm leading! Can you believe it?",
    "moved_into_last": "I'm still having fun back here!",
    "rounded_mark": "Round we go! Whee!",
    "first_across_start": "Best start ever!",
    "finished_race": "That was so much fun!",
    "prestart": "I'm so excited!",
    "start_planing": "We're flying now! Yippee!",
    "random": "Isn't sailing the best?"
  }
};
