// ============================================
// Clear for Action! — Static Game Data
// ============================================

// --- Nationalities & Force Default Ratings ---
export const NATIONALITIES = [
  { id: 'British',    name: 'British Navy',   command: 13, seamanship: 13, gunnery: 13, closeAction: 11 },
  { id: 'French',     name: 'French Navy',    command: 12, seamanship: 13, gunnery: 12, closeAction: 11 },
  { id: 'Spanish',    name: 'Spanish Navy',   command: 10, seamanship: 11, gunnery: 10, closeAction: 12 },
  { id: 'Dutch',      name: 'Dutch Navy',     command: 12, seamanship: 13, gunnery: 12, closeAction: 11 },
  { id: 'American',   name: 'American Navy',  command: 12, seamanship: 12, gunnery: 13, closeAction: 11 },
  { id: 'Ottoman',    name: 'Ottoman Navy',   command: 10, seamanship: 11, gunnery: 9,  closeAction: 12 },
  { id: 'Minor Navy', name: 'Minor Navy',     command: 10, seamanship: 11, gunnery: 10, closeAction: 10 },
  { id: 'Privateers', name: 'Privateers',     command: 11, seamanship: 13, gunnery: 12, closeAction: 11 },
  { id: 'Pirates',    name: 'Pirates',         command: 10, seamanship: 12, gunnery: 10, closeAction: 13 },
  { id: 'Merchants',  name: 'Merchants',       command: 9,  seamanship: 10, gunnery: 9,  closeAction: 9  },
];

// --- Crew Ratings ---
export const CREW_RATINGS = [
  { id: 'landsmen',  name: 'Landsmen (Green)' },
  { id: 'ordinary',  name: 'Ordinary (Regular)' },
  { id: 'able',      name: 'Able (Veteran)' },
  { id: 'crack',     name: 'Crack (Elite)' },
];

// --- Abilities ---
export const ABILITIES = [
  { id: 'steady-hand',       name: 'Steady Hand',       effect: 'Reroll the first failed Seamanship or Gunnery test.' },
  { id: 'well-built',        name: 'Well Built',        effect: 'Ignore the first hull critical.' },
  { id: 'weatherly',         name: 'Weatherly',         effect: 'Gain +1 speed or +1 Maneuver when sailing Close-Hauled.' },
  { id: 'good-in-a-crisis',  name: 'Good in a Crisis',  effect: 'Only suffer -1 penalty to Command when Unsteady.' },
  { id: 'captains-calm',     name: "Captain's Calm",    effect: 'Reroll the first failed Strike Check.' },
  { id: 'practiced-gunnery', name: 'Practiced Gunnery', effect: 'Once per broadside, reroll one Gunnery roll.' },
  { id: 'calm-under-fire',   name: 'Calm under Fire',   effect: '+1 to Command tests to avoid striking.' },
  { id: 'practice-aim',      name: 'Practice Aim',      effect: '+1 Gunnery at long range.' },
  { id: 'balanced-hull',     name: 'Balanced Hull',     effect: 'May treat weather one step better (e.g. heavy as normal).' },
  { id: 'handy-as-a-cutter', name: 'Handy as a Cutter', effect: 'May reroll Tacking tests, but must keep the new result.' },
  { id: 'damn-the-risk',     name: 'Damn the Risk!',    effect: 'Add +1 Gunnery within 1" of the target.' },
  { id: 'flash-of-brilliance', name: 'Flash of Brilliance', effect: 'Once per game, roll twice for a test and keep the better result.' },
  { id: 'fine-french-lines', name: 'Fine French Lines', effect: 'Increase reaching and running speed by one.' },
  { id: 'pride-of-the-duel', name: 'Pride of the Duel', effect: 'When fighting a single opponent, if damage is taken that turn, gain +1 Gunnery.' },
  { id: 'strategist',        name: 'Strategist',        effect: "Once per game, choose the ship's place in the activation order." },
  { id: 'patient-aim',       name: 'Patient Aim',       effect: 'Once per game, skip firing for a full turn to gain +2 Gunnery next turn.' },
  { id: 'organize-the-crew', name: 'Organize the Crew', effect: 'If no enemy within medium range at end of turn, gain +1 Command next turn.' },
  { id: 'cunning-maneuver',  name: 'Cunning Maneuver',  effect: 'Once per game, make one turn before firing a broadside (if not stationary).' },
  { id: 'grace-of-the-sea',  name: 'Grace of the Sea',  effect: 'May reroll grounding and collision tests. Must keep the new result.' },
  { id: 'stand-by-captain',  name: 'Stand by the Captain', effect: 'May ignore the effects of the first officer critical.' },
  { id: 'inspiring',         name: 'Inspiring',         effect: 'May reroll Command tests to Rally the Crew, but must keep the new result.' },
  { id: 'follow-me',         name: 'Follow Me!',        effect: 'If this ship is engaged in Close Action, all friendly ships gain +1 to Command tests.' },
  { id: 'push-the-crew',     name: 'Push the Crew',     effect: 'Once per game, gain +2 speed for two turns, but -2 Command during same period.' },
  { id: 'no-retreat',        name: 'No Retreat',        effect: 'Ignore the first failed Strike check.' },
  { id: 'barrels-for-ballast', name: 'Barrels for Ballast', effect: 'Ignore the first hull critical.' },
  { id: 'fortunes-favorite', name: "Fortune's Favorite", effect: 'Once per game, reroll any one test. The new result must be kept.' },
  { id: 'nerves-of-glass',   name: 'Nerves of Glass',   effect: 'After taking broadside damage, roll Command test. If failed, make a random turn.' },
  { id: 'sea-wolf',          name: 'Sea Wolf',          effect: 'Gain +1 Command when within 6" of an enemy flagship.' },
  { id: 'drilled-gunnery',   name: 'Drilled Gunnery',   effect: 'Reroll 1 gunnery roll per turn.' },
  { id: 'crack-gunnery',     name: 'Crack Gunnery',     effect: 'Gain +1 Gunnery at short range.' },
  { id: 'handy',             name: 'Handy',             effect: 'Gain +1 Seamanship to tacking checks.' },
  { id: 'lucky',             name: 'Lucky',             effect: 'Force a reroll on three dice per game (yours or opponent\'s).' },
  { id: 'steady',            name: 'Steady',            effect: 'No penalty for being unsteady.' },
  { id: 'bold',              name: 'Bold',              effect: '+1 Command when initiating boarding or Close Action.' },
  { id: 'pursuit',           name: 'Pursuit',           effect: '+1 speed when chasing an enemy ship directly downwind.' },
  { id: 'quick-guns',        name: 'Quick Guns',        effect: 'May reload and fire one broadside per turn without penalty.' },
];

// --- Gun Types Reference ---
// Columns: type, damage, short range, medium range, long range
export const GUN_TYPES = [
  { type: '1-pdr',         damage: 11, short: 1, medium: 3,  long: 6,  isCarronade: false },
  { type: '2-pdr',         damage: 13, short: 1, medium: 5,  long: 10, isCarronade: false },
  { type: '4-pdr',         damage: 15, short: 2, medium: 6,  long: 14, isCarronade: false },
  { type: '6-pdr',         damage: 17, short: 3, medium: 7,  long: 16, isCarronade: false },
  { type: '8-pdr',         damage: 18, short: 3, medium: 8,  long: 18, isCarronade: false },
  { type: '9-pdr',         damage: 19, short: 3, medium: 9,  long: 21, isCarronade: false },
  { type: '12-pdr',        damage: 21, short: 4, medium: 10, long: 23, isCarronade: false },
  { type: '18-pdr',        damage: 23, short: 4, medium: 12, long: 25, isCarronade: false },
  { type: '24-pdr',        damage: 26, short: 4, medium: 14, long: 27, isCarronade: false },
  { type: '32-pdr',        damage: 29, short: 5, medium: 15, long: 30, isCarronade: false },
  { type: '36-pdr',        damage: 30, short: 5, medium: 16, long: 32, isCarronade: false },
  { type: '42-pdr',        damage: 32, short: 5, medium: 17, long: 34, isCarronade: false },
  { type: '64-pdr',        damage: 36, short: 6, medium: 18, long: 36, isCarronade: false },
  { type: '6-pdr carr.',   damage: 20, short: 3, medium: 0,  long: 0,  isCarronade: true },
  { type: '12-pdr carr.',  damage: 24, short: 4, medium: 0,  long: 0,  isCarronade: true },
  { type: '18-pdr carr.',  damage: 26, short: 4, medium: 0,  long: 0,  isCarronade: true },
  { type: '24-pdr carr.',  damage: 28, short: 4, medium: 0,  long: 0,  isCarronade: true },
  { type: '32-pdr carr.',  damage: 30, short: 5, medium: 0,  long: 0,  isCarronade: true },
  { type: '42-pdr carr.',  damage: 32, short: 5, medium: 0,  long: 0,  isCarronade: true },
  { type: '64-pdr carr.',  damage: 38, short: 6, medium: 0,  long: 0,  isCarronade: true },
];

export const GUN_FACINGS = [
  { id: 'broadside', name: 'Broadside', abbr: 'BS' },
  { id: 'bow',       name: 'Bow Chase', abbr: 'Bow' },
  { id: 'stern',     name: 'Stern Chase', abbr: 'Stern' },
];

// --- Wind Settings ---
export const WIND_DIRECTIONS = ['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW'];
export const WIND_STRENGTHS = [
  { id: 'calm',     name: 'Calm' },
  { id: 'light',    name: 'Light' },
  { id: 'moderate', name: 'Moderate' },
  { id: 'heavy',    name: 'Heavy' },
  { id: 'storm',    name: 'Storm' },
];

// --- Sail Settings ---
export const SAIL_SETTINGS = [
  { id: 'hoveTo', name: 'Hove To' },
  { id: 'reefed', name: 'Reefed' },
  { id: 'battle', name: 'Battle' },
  { id: 'full',   name: 'Full' },
];

// --- Ship Class Templates ---
// Stats from the rulebook "Ship Default Stats" table
// Columns: defense, defense2, morale, crew, rigging, hull, maneuver, fullCH, fullReach, fullRun, fire, leak, steering, mast, officer
export const SHIP_TEMPLATES = [
  // --- Warships ---
  {
    id: 'boat',
    name: 'Boat / Launch / Gunboat',
    gunRange: '1 - 2 guns',
    category: 'warship',
    tonnageRange: '20 - 110',
    defense: 1, defense2: 3,
    morale: 5, crew: 1, rigging: 3, hull: 4,
    maneuver: 6,
    speed: { closeHauled: 4, reaching: 5, running: 4 },
    criticals: { fire: 1, leak: 1, steering: 1, mast: 0, officer: 1 },
  },
  {
    id: 'cutter',
    name: 'Cutter',
    gunRange: '2 - 6 guns',
    category: 'warship',
    tonnageRange: '80 - 180',
    defense: 3, defense2: 4,
    morale: 6, crew: 1, rigging: 4, hull: 5,
    maneuver: 6,
    speed: { closeHauled: 5, reaching: 6, running: 5 },
    criticals: { fire: 2, leak: 2, steering: 1, mast: 1, officer: 1 },
  },
  {
    id: 'small-brig',
    name: 'Small Brig / Schooner',
    gunRange: '6 - 10 guns',
    category: 'warship',
    tonnageRange: '140 - 230',
    defense: 5, defense2: 6,
    morale: 8, crew: 2, rigging: 5, hull: 6,
    maneuver: 5,
    speed: { closeHauled: 6, reaching: 7, running: 6 },
    criticals: { fire: 2, leak: 3, steering: 1, mast: 2, officer: 1 },
  },
  {
    id: 'brig-sloop',
    name: 'Brig / Sloop / Small Corvette',
    gunRange: '12 - 18 guns',
    category: 'warship',
    tonnageRange: '230 - 400',
    defense: 7, defense2: 8,
    morale: 9, crew: 3, rigging: 6, hull: 11,
    maneuver: 4,
    speed: { closeHauled: 6, reaching: 8, running: 7 },
    criticals: { fire: 2, leak: 4, steering: 1, mast: 2, officer: 2 },
  },
  {
    id: 'light-frigate',
    name: 'Light Frigate / Corvette',
    gunRange: '20 - 28 guns',
    category: 'warship',
    tonnageRange: '450 - 650',
    defense: 9, defense2: 10,
    morale: 12, crew: 4, rigging: 8, hull: 15,
    maneuver: 3,
    speed: { closeHauled: 7, reaching: 10, running: 9 },
    criticals: { fire: 3, leak: 5, steering: 2, mast: 3, officer: 2 },
  },
  {
    id: 'frigate',
    name: 'Frigate',
    gunRange: '30 - 40 guns',
    category: 'warship',
    tonnageRange: '900 - 1100',
    defense: 11, defense2: 11,
    morale: 16, crew: 6, rigging: 9, hull: 23,
    maneuver: 3,
    speed: { closeHauled: 8, reaching: 11, running: 10 },
    criticals: { fire: 3, leak: 6, steering: 2, mast: 3, officer: 2 },
  },
  {
    id: 'heavy-frigate',
    name: 'Heavy Frigate',
    gunRange: '42 - 50 guns',
    category: 'warship',
    tonnageRange: '1200 - 1600',
    defense: 13, defense2: 13,
    morale: 20, crew: 7, rigging: 12, hull: 28,
    maneuver: 3,
    speed: { closeHauled: 9, reaching: 12, running: 11 },
    criticals: { fire: 4, leak: 7, steering: 2, mast: 3, officer: 3 },
  },
  {
    id: '4th-rate',
    name: '4th Rate / Small 3rd Rate',
    gunRange: '50 - 64 guns',
    category: 'warship',
    tonnageRange: '1050 - 1700',
    defense: 15, defense2: 16,
    morale: 22, crew: 8, rigging: 14, hull: 32,
    maneuver: 2,
    speed: { closeHauled: 7, reaching: 10, running: 9 },
    criticals: { fire: 4, leak: 9, steering: 3, mast: 3, officer: 3 },
  },
  {
    id: '3rd-rate',
    name: '3rd Rate',
    gunRange: '70 - 80 guns',
    category: 'warship',
    tonnageRange: '1600 - 2100',
    defense: 17, defense2: 17,
    morale: 24, crew: 9, rigging: 15, hull: 34,
    maneuver: 2,
    speed: { closeHauled: 7, reaching: 10, running: 9 },
    criticals: { fire: 4, leak: 9, steering: 3, mast: 3, officer: 3 },
  },
  {
    id: '2nd-rate',
    name: '2nd Rate',
    gunRange: '82 - 100 guns',
    category: 'warship',
    tonnageRange: '2000 - 2300',
    defense: 19, defense2: 18,
    morale: 30, crew: 10, rigging: 17, hull: 37,
    maneuver: 1,
    speed: { closeHauled: 7, reaching: 10, running: 9 },
    criticals: { fire: 5, leak: 10, steering: 3, mast: 3, officer: 4 },
  },
  {
    id: '1st-rate',
    name: '1st Rate',
    gunRange: '100+ guns',
    category: 'warship',
    tonnageRange: '2100 - 2500',
    defense: 20, defense2: 19,
    morale: 32, crew: 12, rigging: 20, hull: 40,
    maneuver: 1,
    speed: { closeHauled: 7, reaching: 10, running: 9 },
    criticals: { fire: 5, leak: 10, steering: 3, mast: 3, officer: 4 },
  },

  // --- Merchants & Traders ---
  {
    id: 'merchant-boat',
    name: 'Boat / Launch / Lighter',
    gunRange: '0 guns',
    category: 'merchant',
    tonnageRange: '10 - 60',
    defense: 1, defense2: 2,
    morale: 3, crew: 1, rigging: 2, hull: 3,
    maneuver: 6,
    speed: { closeHauled: 3, reaching: 4, running: 4 },
    criticals: { fire: 1, leak: 1, steering: 1, mast: 0, officer: 0 },
  },
  {
    id: 'smack',
    name: 'Smack',
    gunRange: '0 guns',
    category: 'merchant',
    tonnageRange: '20 - 60',
    defense: 2, defense2: 3,
    morale: 4, crew: 1, rigging: 3, hull: 4,
    maneuver: 6,
    speed: { closeHauled: 4, reaching: 5, running: 4 },
    criticals: { fire: 1, leak: 1, steering: 1, mast: 1, officer: 0 },
  },
  {
    id: 'hoy',
    name: 'Hoy',
    gunRange: '0 guns',
    category: 'merchant',
    tonnageRange: '50 - 80',
    defense: 2, defense2: 3,
    morale: 4, crew: 1, rigging: 3, hull: 4,
    maneuver: 5,
    speed: { closeHauled: 3, reaching: 5, running: 4 },
    criticals: { fire: 1, leak: 2, steering: 1, mast: 1, officer: 0 },
  },
  {
    id: 'felucca',
    name: 'Felucca / Tartane',
    gunRange: '0 guns',
    category: 'merchant',
    tonnageRange: '30 - 100',
    defense: 2, defense2: 3,
    morale: 5, crew: 1, rigging: 3, hull: 4,
    maneuver: 6,
    speed: { closeHauled: 4, reaching: 6, running: 6 },
    criticals: { fire: 1, leak: 1, steering: 1, mast: 1, officer: 0 },
  },
  {
    id: 'lugger',
    name: 'Lugger',
    gunRange: '0 - 4 guns',
    category: 'merchant',
    tonnageRange: '50 - 120',
    defense: 3, defense2: 4,
    morale: 6, crew: 1, rigging: 4, hull: 5,
    maneuver: 6,
    speed: { closeHauled: 4, reaching: 7, running: 6 },
    criticals: { fire: 1, leak: 2, steering: 1, mast: 1, officer: 0 },
  },
  {
    id: 'merchant-cutter',
    name: 'Cutter (merchant)',
    gunRange: '0 - 4 guns',
    category: 'merchant',
    tonnageRange: '80 - 150',
    defense: 3, defense2: 4,
    morale: 6, crew: 1, rigging: 4, hull: 5,
    maneuver: 6,
    speed: { closeHauled: 5, reaching: 7, running: 6 },
    criticals: { fire: 2, leak: 2, steering: 1, mast: 1, officer: 0 },
  },
  {
    id: 'merchant-schooner',
    name: 'Schooner (merchant)',
    gunRange: '0 - 6 guns',
    category: 'merchant',
    tonnageRange: '100 - 200',
    defense: 4, defense2: 5,
    morale: 6, crew: 1, rigging: 5, hull: 6,
    maneuver: 6,
    speed: { closeHauled: 5, reaching: 7, running: 6 },
    criticals: { fire: 2, leak: 2, steering: 1, mast: 1, officer: 0 },
  },
  {
    id: 'merchant-brigantine',
    name: 'Brigantine (merchant)',
    gunRange: '0 - 4 guns',
    category: 'merchant',
    tonnageRange: '50 - 150',
    defense: 4, defense2: 5,
    morale: 6, crew: 1, rigging: 5, hull: 6,
    maneuver: 6,
    speed: { closeHauled: 4, reaching: 6, running: 6 },
    criticals: { fire: 2, leak: 2, steering: 1, mast: 1, officer: 0 },
  },
  {
    id: 'polacca-xebec',
    name: 'Polacca / Xebec',
    gunRange: '0 - 8 guns',
    category: 'merchant',
    tonnageRange: '100 - 250',
    defense: 4, defense2: 5,
    morale: 6, crew: 1, rigging: 5, hull: 6,
    maneuver: 5,
    speed: { closeHauled: 5, reaching: 7, running: 8 },
    criticals: { fire: 2, leak: 2, steering: 1, mast: 1, officer: 0 },
  },
  {
    id: 'snow',
    name: 'Snow',
    gunRange: '0 - 6 guns',
    category: 'merchant',
    tonnageRange: '150 - 350',
    defense: 5, defense2: 6,
    morale: 7, crew: 2, rigging: 6, hull: 8,
    maneuver: 4,
    speed: { closeHauled: 5, reaching: 7, running: 6 },
    criticals: { fire: 2, leak: 3, steering: 1, mast: 2, officer: 0 },
  },
  {
    id: 'merchant-brig',
    name: 'Brig (merchant)',
    gunRange: '0 - 8 guns',
    category: 'merchant',
    tonnageRange: '180 - 350',
    defense: 5, defense2: 6,
    morale: 7, crew: 2, rigging: 6, hull: 9,
    maneuver: 4,
    speed: { closeHauled: 5, reaching: 7, running: 6 },
    criticals: { fire: 2, leak: 3, steering: 1, mast: 2, officer: 0 },
  },
  {
    id: 'collier',
    name: 'Collier',
    gunRange: '0 - 4 guns',
    category: 'merchant',
    tonnageRange: '280 - 380',
    defense: 5, defense2: 6,
    morale: 7, crew: 2, rigging: 6, hull: 10,
    maneuver: 4,
    speed: { closeHauled: 5, reaching: 6, running: 6 },
    criticals: { fire: 2, leak: 4, steering: 1, mast: 2, officer: 0 },
  },
  {
    id: 'fluyt',
    name: 'Fluyt',
    gunRange: '0 - 6 guns',
    category: 'merchant',
    tonnageRange: '300 - 600',
    defense: 6, defense2: 7,
    morale: 7, crew: 2, rigging: 7, hull: 10,
    maneuver: 3,
    speed: { closeHauled: 5, reaching: 7, running: 6 },
    criticals: { fire: 2, leak: 4, steering: 1, mast: 2, officer: 0 },
  },
  {
    id: 'barque',
    name: 'Barque / Small Ship-rigged Merchant',
    gunRange: '0 - 8 guns',
    category: 'merchant',
    tonnageRange: '300 - 700',
    defense: 6, defense2: 7,
    morale: 7, crew: 2, rigging: 7, hull: 12,
    maneuver: 3,
    speed: { closeHauled: 6, reaching: 8, running: 7 },
    criticals: { fire: 2, leak: 5, steering: 2, mast: 2, officer: 0 },
  },
  {
    id: 'west-indiaman',
    name: 'West Indiaman',
    gunRange: '6 - 16 guns',
    category: 'merchant',
    tonnageRange: '400 - 800',
    defense: 7, defense2: 8,
    morale: 8, crew: 3, rigging: 8, hull: 14,
    maneuver: 3,
    speed: { closeHauled: 6, reaching: 8, running: 7 },
    criticals: { fire: 3, leak: 6, steering: 2, mast: 2, officer: 0 },
  },
  {
    id: 'packet-ship',
    name: 'Packet Ship',
    gunRange: '4 - 12 guns',
    category: 'merchant',
    tonnageRange: '400 - 900',
    defense: 7, defense2: 8,
    morale: 9, crew: 2, rigging: 8, hull: 13,
    maneuver: 4,
    speed: { closeHauled: 7, reaching: 9, running: 8 },
    criticals: { fire: 4, leak: 6, steering: 2, mast: 2, officer: 0 },
  },
  {
    id: 'east-indiaman',
    name: 'East Indiaman',
    gunRange: '20 - 36 guns',
    category: 'merchant',
    tonnageRange: '800 - 1400',
    defense: 8, defense2: 9,
    morale: 9, crew: 4, rigging: 10, hull: 18,
    maneuver: 2,
    speed: { closeHauled: 6, reaching: 8, running: 7 },
    criticals: { fire: 3, leak: 7, steering: 2, mast: 3, officer: 1 },
  },
  {
    id: 'large-indiaman',
    name: 'Large Indiaman',
    gunRange: '30 - 50 guns',
    category: 'merchant',
    tonnageRange: '1200 - 1600',
    defense: 9, defense2: 10,
    morale: 10, crew: 5, rigging: 11, hull: 20,
    maneuver: 2,
    speed: { closeHauled: 6, reaching: 9, running: 8 },
    criticals: { fire: 3, leak: 8, steering: 2, mast: 3, officer: 1 },
  },
];

// --- Helper: Create blank ship from template ---
export function createShipFromTemplate(templateId) {
  const t = SHIP_TEMPLATES.find(s => s.id === templateId);
  if (!t) return createBlankShip();
  return {
    ...createBlankShip(),
    classAndRating: t.name + (t.gunRange ? ` (${t.gunRange})` : ''),
    tonnage: t.tonnageRange,
    movement: { maneuver: t.maneuver, defense: t.defense },
    speed: { ...t.speed },
    vitals: { morale: t.morale, crew: t.crew, rigging: t.rigging, hull: t.hull },
    criticals: { ...t.criticals },
    sourceTemplate: t.id,
  };
}

export function createBlankShip() {
  return {
    id: '',  // set by caller
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    name: '',
    nationality: 'British',
    classAndRating: '',
    description: '',
    yearLaunched: '',
    tonnage: '',
    complement: '',
    shipImage: null,
    captain: { name: '', rank: '', image: null, crewRating: 'ordinary' },
    abilities: [],
    skills: { command: 13, seamanship: 13, gunnery: 13, closeAction: 11 },
    movement: { maneuver: 3, defense: 10 },
    speed: { closeHauled: 0, reaching: 0, running: 0 },
    vitals: { morale: 10, crew: 4, rigging: 6, hull: 10 },
    guns: [],
    criticals: { fire: 2, leak: 2, steering: 2, mast: 2, officer: 2 },
    broadsideWeight: 0,
    sourceTemplate: null,
  };
}

// --- Helper: Create GameShip from a Ship template ---
export function createGameShip(ship) {
  const { deepClone } = { deepClone: obj => JSON.parse(JSON.stringify(obj)) };
  const gs = deepClone(ship);
  gs.sourceShipId = ship.id;
  gs.displayName = ship.name;
  gs.currentVitals = { ...ship.vitals };
  gs.currentGuns = (ship.guns || []).map(g => ({ gunId: g.id, remainingCount: g.count }));
  gs.currentCriticals = { fire: 0, leak: 0, steering: 0, mast: 0, officer: 0 };
  gs.sailSetting = 'battle';
  gs.status = { grappled: false, aground: false, struck: false, firstBroadside: { port: true, starboard: true } };
  gs.notes = '';
  gs.collapsed = true;
  return gs;
}
