// regatta/js/ai/roster.js — the AI fleet: archetypes, traits, stats, and the
// 100-character roster (AI_CONFIG). Classic script sharing the global scope;
// loads before ai/bot.js. Extracted verbatim from script.js (refactor 2026-08-24).
// NOTE: eval/gen_roster.js, gen_archive.js, rate_report.js, rate_run.js,
// tier_model.py, tier_grid.py, gen_stats.py and art/review.py regex-scrape
// `const AI_CONFIG = [` ... `\n];` from THIS file — keep that exact shape.


// AI Configuration
// --- Racing Archetypes ---------------------------------------------------
// Each AI character has ONE archetype: a persona layer of behavioral traits
// consumed by BotController, plus a threat/weakness line surfaced to the
// player. Design rule: every archetype changes HOW the boat races, paired
// with an exploitable weakness — never a flat power boost. All trait values
// default to current fleet behavior (DEFAULT_TRAITS) so an archetype only
// diverges where it means to.
//   aggro        -1..1  avoidance margin scale (+ = shaves give-way bubbles)
//   startBufAdj  secs   added to the start crossing-run buffer (+ = commits earlier)
//   shiftSense   x      multiplier on the lift/header tack bonus
//   windFast     x      multiplier on the wind-tracker EMA rate (faster read)
//   pressureSense x     multiplier on the pressure-seeking bonus
//   cornerScale  x      multiplier on gate approach inset (<1 = aims closer to the mark)
//   cornerRound  x      multiplier on the rounding offset — KEEP >= 1.0 unless you
//                       want mark contact; tight offsets clip the mark, and with
//                       turn-penalties each clip costs a ~15-25s spiral episode
//   sideCommit   0/1    gambler: pick a side of the beat per leg and bang it
//   cover        0..1   leech: bonus for matching the nearest rival's tack
//   laylineTight x      multiplier on the layline trigger window (<1 = calls it later/closer)
//   overTack     x      divisor on tack stickiness (>1 = tacks more, pays the manoeuvre)
//   roundTurn    u|null  override of the rounding carve pull (fleet default 80)
//
// speedScale (a flat boatspeed multiplier, used only by shift at 0.97) was REMOVED.
// Measured over 1200 paired seeds it cost the archetype 4.68s +/-0.94 while every
// other archetype sat within +/-1.0s of zero: a ~6.45s tax against 1.77s of benefit
// from the reading traits. A flat multiplier is the bluntest possible nerf — it
// taxes every second of the race whether or not the advantage is expressing — so
// shift's weakness is now situational instead (see overTack). guidelines/skills.md 3.3.
const DEFAULT_TRAITS = { aggro: 0, startBufAdj: 0, shiftSense: 1.0, windFast: 1.0, pressureSense: 1.0, cornerScale: 1.0, cornerRound: 1.0, sideCommit: 0, cover: 0, laylineTight: 1.0, overTack: 1.0, roundTurn: null };

const ARCHETYPES = {
    bully: {
        label: 'Line Bully',
        threat: 'Crowds rivals into flinching first — gives you no room at the start or in traffic.',
        weakness: 'Runs hot: the fights cost penalties and pace. Stay clean and sail past the wreckage.',
        traits: { aggro: 0.7 },
    },
    rocket: {
        label: 'Rocket Start',
        threat: 'First off the line almost every race and gone with clear air.',
        weakness: 'Fades once the fleet reaches full speed — reel them in mid-leg and hold your lane.',
        traits: { startBufAdj: -0.1 },
    },
    shift: {
        label: 'Shift Whisperer',
        threat: 'Reads the wind before anyone. In shifty air, going the other way is usually wrong.',
        weakness: 'Slow in a straight line — beat them on pure pace when the breeze goes steady.',
        traits: { shiftSense: 1.5, windFast: 1.4, pressureSense: 1.15, overTack: 1.35 },
    },
    freight: {
        label: 'Freight Train',
        threat: 'Carries speed nothing can stop — never cross them late.',
        weakness: 'Wide, lumbering roundings — attack at every mark.',
        traits: { cornerScale: 1.25, cornerRound: 1.25, laylineTight: 1.1 },
    },
    corner: {
        label: 'Corner Artist',
        threat: 'Surgical mark roundings — gains boat lengths at every gate.',
        weakness: 'Backs off in a crowd — lean on them and they yield the lane.',
        traits: { cornerScale: 0.85, aggro: -0.15, roundTurn: 130 },
    },
    gambler: {
        label: 'Corner Gambler',
        threat: 'Bangs a corner of the course. When the shift favors them, they come back untouchable.',
        weakness: 'Ignores the wind to get there — most days the corner buries them.',
        traits: { sideCommit: 1, shiftSense: 0.4 },
    },
    leech: {
        label: 'The Leech',
        threat: 'Locks onto the nearest rival and matches every tack, sitting on their wind.',
        weakness: 'Loses time shadowing — split hard and stretch them past their patience.',
        traits: { cover: 0.8 },
    },
    metronome: {
        label: 'Metronome',
        threat: 'Never blinks, never blunders — always in the hunt at the finish.',
        weakness: 'No spikes: one well-timed risk is worth more than their whole race.',
        traits: { laylineTight: 0.85, startBufAdj: -0.05 },
    },
};

// Generic archetype call-outs used when a character has no bespoke quote for
// a behavior trigger (bully engaging, gambler picking a side, leech locking on).
const ARCHETYPE_CALLS = {
    bully_engage: ["My water. Find another lane!", "You do NOT want this fight.", "Coming through — flinch or foul."],
    side_pick: ["I like the look of that corner.", "See you at the shift, suckers.", "All in. One side, one story."],
    cover_lock: ["Nice wind you've got there. Mine now.", "Wherever you go, I go.", "You tack, I tack. Simple."],
};

// The full stat set. The first seven are performance; the last three are the
// conditions/craft axes added in the roster rework (guidelines/skills.md 4).
const STAT_DEFAULTS = {
    acceleration: 0, momentum: 0, handling: 0, upwind: 0, reach: 0, downwind: 0, pressure: 0,
    lightAir: 0, heavyAir: 0, memory: 0
};
// Only the performance stats take the difficulty bonus. A flat +4 on lightAir AND
// heavyAir would make every AI boat good at both extremes at once — a fleet-wide
// power boost, not a difficulty setting. And "+4 memory" is not a difficulty at all:
// a longer retention window is a trade-off (slow to notice real change), not an
// improvement, so scaling it with difficulty would be meaningless.
const BONUS_STATS = ['acceleration', 'momentum', 'handling', 'upwind', 'reach', 'downwind', 'pressure'];

// Wind-groove bands for lightAir / heavyAir. Quadratic in normalised depth into the
// band because marginal difficulty escalates: 9 knots versus 10 is nothing, 6 versus
// 7 is everything; 17 knots is manageable, 20 is a handful. Moderate air (10-16) is
// untouched by both, so the other stats decide a mid-range race.
const WIND_GROOVE = { lightFull: 6, lightNone: 10, heavyNone: 16, heavyFull: 20, perPoint: 0.012 };
function windGrooveFactor(stats, wind) {
    const g = WIND_GROOVE;
    let f = 1.0;
    if (stats.lightAir && wind < g.lightNone) {
        const t = Math.min(1, (g.lightNone - wind) / (g.lightNone - g.lightFull));
        f += stats.lightAir * g.perPoint * t * t;
    }
    if (stats.heavyAir && wind > g.heavyNone) {
        const t = Math.min(1, (wind - g.heavyNone) / (g.heavyFull - g.heavyNone));
        f += stats.heavyAir * g.perPoint * t * t;
    }
    return Math.max(0.5, f);
}

// Difficulty: flat bonus added to every performance stat of every AI boat at construction.
// The player's boat has all-zero stats, so this makes the whole fleet faster
// and sharper without changing character-to-character balance or archetype
// identities. 0 = original difficulty; each point is worth roughly 1.2-1.8%
// boatspeed depending on point of sail, plus accel/handling/gust response.
const AI_STAT_BONUS = 4;

const AI_CONFIG = [
    { name: 'Cheer', creature: 'Pom Pom Crab', hull: '#FF9ECF', spinnaker: '#00E5FF', spinnaker2: '#FF9ECF', spinnaker3: '#FFE066', sail: '#FFFFFF', cockpit: '#FFFFFF', personality: "Cheerful and fun loving, always positive and enthuiastic.", beat: 'Out-spike her steady beat — she has no pace off the wind.', archetype: 'metronome', stats: { acceleration: 2, momentum: -2, handling: 4, upwind: 1, reach: -2, downwind: -1, pressure: 5, lightAir: 2, heavyAir: -1, memory: -1 } },
    { name: 'Bixby', creature: 'Sea Otter', hull: '#0046ff', spinnaker: '#FFD400', spinnaker2: '#0046ff', sail: '#FFFFFF', cockpit: '#C9CCD6', personality: "Relaxed veteran who instinctively finds perfect wind." , beat: 'Beat him to the top mark — upwind he is merely mortal.', archetype: 'shift', stats: { acceleration: -2, momentum: -3, handling: -1, upwind: 0, reach: 3, downwind: 5, pressure: 1, lightAir: 1, heavyAir: 2, memory: 5 } },
    { name: 'Skim', creature: 'Flying Fish', hull: '#8FD3FF', spinnaker: '#FF2D95', spinnaker2: '#FFFFFF', spinnaker3: '#8FD3FF', sail: '#FFFFFF', cockpit: '#AEB4BF', personality: "Flashy opportunist thriving on speed bursts." , beat: 'Survive her start, then turn hard and often — she hates corners.', archetype: 'rocket', stats: { acceleration: 5, momentum: 0, handling: -4, upwind: 0, reach: -4, downwind: -1, pressure: 0, lightAir: 4, heavyAir: -4, memory: -2 } },
    { name: 'Wobble', creature: 'Platypus', hull: '#FF8C1A', spinnaker: '#7B4FD4', spinnaker2: '#FF8C1A', sail: '#FFFFFF', cockpit: '#B0B0B0', personality: "Awkward, unpredictable, deadly effective in chaos." , beat: 'Ignores the wind to get there — sail the middle and collect.', archetype: 'gambler', stats: { acceleration: 5, momentum: -1, handling: -2, upwind: -3, reach: 3, downwind: 0, pressure: 4, lightAir: 2, heavyAir: -2, memory: 1 } },
    { name: 'Pinch', creature: 'American Lobster', hull: '#E10600', spinnaker: '#FFFFFF', spinnaker2: '#E10600', sail: '#FFFFFF', cockpit: '#5A5A5A', personality: "Aggressive bully dominating the starting line." , beat: 'Stay clean upwind, then walk away downwind — he parks there.', archetype: 'bully', stats: { acceleration: 1, momentum: -2, handling: 0, upwind: 2, reach: -1, downwind: -5, pressure: 2, lightAir: -2, heavyAir: 2, memory: 3 } },
    { name: 'Bruce', creature: 'Great White Shark', hull: '#121212', spinnaker: '#ff0606', spinnaker2: '#000000', sail: '#FFFFFF', cockpit: '#3A3A3A', personality: "Cold, relentless presence forcing others to react." , beat: 'Force restarts and tacking duels — he cannot get moving again.', archetype: 'bully', stats: { acceleration: -5, momentum: -4, handling: -5, upwind: 1, reach: 3, downwind: 4, pressure: 2, lightAir: -4, heavyAir: 5, memory: 3 } },
    { name: 'Strut', creature: 'Flamingo', hull: '#FF4F9A', spinnaker: '#1A1A1A', spinnaker2: '#FF4F9A', spinnaker3: '#FFFFFF', sail: '#FFFFFF', cockpit: '#B0BEC5', personality: "Stylish confidence with daring, showy sailing." , beat: 'Push her into maneuvers — every turn costs her the strut.', archetype: 'metronome', stats: { acceleration: -3, momentum: -3, handling: -5, upwind: 5, reach: -2, downwind: 1, pressure: 2, lightAir: 2, heavyAir: -1, memory: 0 } },
    { name: 'Gasket', creature: 'American Beaver', hull: '#FFE600', spinnaker: '#1F6FB2', spinnaker2: '#FFE600', sail: '#000000', cockpit: '#C4BEB2', personality: "Methodical and stubborn, grinding out advantages." , beat: 'Match him upwind, pull away when the spinnakers go up.', archetype: 'metronome', stats: { acceleration: 3, momentum: -3, handling: 3, upwind: 0, reach: 0, downwind: -4, pressure: -3, lightAir: 4, heavyAir: -3, memory: 4 } },
    { name: 'Chomp', creature: 'Saltwater Crocodile', hull: '#2ECC71', spinnaker: '#9CBF28', spinnaker2: '#1A1A1A', sail: '#000000', cockpit: '#C1B58A', personality: "Patient hunter striking without warning." , beat: 'Tack early, tack often — the ambusher cannot follow through turns.', archetype: 'leech', stats: { acceleration: 2, momentum: 3, handling: -5, upwind: 1, reach: -3, downwind: -2, pressure: 0, lightAir: 4, heavyAir: 1, memory: 3 } },
    { name: 'Whiskers', creature: 'Walrus', hull: '#C49A6C', spinnaker: '#8E0038', spinnaker2: '#FFFFFF', spinnaker3: '#C49A6C', sail: '#FFFFFF', cockpit: '#ddd3c9', personality: "Massive, steady, unbeatable in heavy conditions." , beat: 'Attack every rounding and reach — the train needs straight track.', archetype: 'freight', stats: { acceleration: -2, momentum: 4, handling: 2, upwind: 0, reach: -5, downwind: 4, pressure: -3, lightAir: -4, heavyAir: 5, memory: 2 } },
    { name: 'Vex', creature: 'Water Dragon', hull: '#0fe367', spinnaker: '#D9D9D9', spinnaker2: '#0fe367', sail: '#FFFFFF', cockpit: '#D0D0D0', personality: "Slippery tactician exploiting tiny mistakes." , beat: 'Lean on him mid-leg — away from corners he is out of tricks.', archetype: 'corner', stats: { acceleration: -3, momentum: -5, handling: 4, upwind: -4, reach: -5, downwind: 1, pressure: 4, lightAir: 2, heavyAir: -1, memory: 2 } },
    { name: 'Hug', creature: 'Ochre Sea Star', hull: '#9900ff', spinnaker: '#E8A6FF', spinnaker2: '#FF9E2C', spinnaker3: '#9900FF', sail: '#FFFFFF', cockpit: '#C9CCD6', personality: "Chill vibes, relentless endurance." , beat: 'Get ahead early — Hug finishes everything she starts, slowly.', archetype: 'metronome', stats: { acceleration: -3, momentum: 1, handling: 0, upwind: 5, reach: 2, downwind: 2, pressure: 5, lightAir: 1, heavyAir: -2, memory: -5 } },
    { name: 'Ripple', creature: 'Bottlenose Dolphin', hull: '#00B3FF', spinnaker: '#FFD400', spinnaker2: '#FFFFFF', sail: '#FFFFFF', cockpit: '#B8C6D1', personality: "Cheerful speedster seeking clean lanes." , beat: 'Drag her into traffic — clean lanes are where she lives.', archetype: 'shift', stats: { acceleration: -2, momentum: -1, handling: -3, upwind: 4, reach: -4, downwind: 5, pressure: 0, lightAir: 0, heavyAir: 2, memory: 5 } },
    { name: 'Clutch', creature: 'Red Rock Crab', hull: '#B00020', spinnaker: '#FFD166', spinnaker2: '#B00020', sail: '#FFFFFF', cockpit: '#6B6B6B', personality: "Defensive and stubborn off the line." , beat: 'Do not engage — sail past while he is busy starting fights.', archetype: 'bully', stats: { acceleration: -5, momentum: 2, handling: -4, upwind: 4, reach: -5, downwind: -2, pressure: 0, lightAir: -1, heavyAir: 1, memory: 0 } },
    { name: 'Glide', creature: 'Wandering Albatross', hull: '#E8F1F8', spinnaker: '#1F4FFF', spinnaker2: '#FFFFFF', spinnaker3: '#B8CEE0', sail: '#000000', cockpit: '#C5CED6', personality: "Patient perfectionist who never blunders." , beat: 'Perfect upwind, lost downwind — make the runs count.', archetype: 'metronome', stats: { acceleration: -4, momentum: 3, handling: 2, upwind: 4, reach: 1, downwind: -5, pressure: 1, lightAir: 3, heavyAir: 4, memory: 3 } },
    { name: 'Fathom', creature: 'Orca', hull: '#1C1C3C', spinnaker: '#3D8BFF', spinnaker2: '#FFFFFF', sail: '#FFFFFF', cockpit: '#3C3F55', personality: "Silent dominance unleashed at full power." , beat: 'Turn the race into corners — momentum cannot help him there.', archetype: 'freight', stats: { acceleration: 0, momentum: 5, handling: -5, upwind: 3, reach: 4, downwind: 4, pressure: 2, lightAir: 0, heavyAir: 5, memory: 5 } },
    { name: 'Scuttle', creature: 'Hermit Crab', hull: '#FFB703', spinnaker: '#3A86FF', spinnaker2: '#FFB703', sail: '#000000', cockpit: '#BFAF92', personality: "Erratic survivor thriving in congestion." , beat: 'Deny the chaos — in a clean race he is just slow.', archetype: 'gambler', stats: { acceleration: -4, momentum: -3, handling: -3, upwind: -3, reach: 1, downwind: -2, pressure: 5, lightAir: 2, heavyAir: -1, memory: -1 } },
    { name: 'Finley', creature: 'Yellowfin Tuna', hull: '#0077B6', spinnaker: '#ffd900', spinnaker2: '#0077B6', sail: '#FFFFFF', cockpit: '#A7B8C8', personality: "Pure speed and relentless pressure." , beat: 'Break cover downwind — his speed lives on the beat.', archetype: 'leech', stats: { acceleration: -2, momentum: -3, handling: -3, upwind: 5, reach: -2, downwind: 1, pressure: -1, lightAir: -1, heavyAir: 4, memory: 2 } },
    { name: 'Torch', creature: 'Fire Salamander', hull: '#FF3B30', spinnaker: '#FFD60A', spinnaker2: '#FF3B30', spinnaker3: '#FFFFFF', sail: '#000000', cockpit: '#5E5E5E', personality: "Explosive starts, reckless aggression." , beat: 'Let the fire burn out — he keeps nothing through lulls or turns.', archetype: 'rocket', stats: { acceleration: 1, momentum: -5, handling: -3, upwind: -1, reach: 4, downwind: -1, pressure: 4, lightAir: 2, heavyAir: -1, memory: 1 } },
    { name: 'Nimbus', creature: 'Spotted Eagle Ray', hull: '#6A7FDB', spinnaker: '#F1F7FF', spinnaker2: '#6A7FDB', sail: '#FFFFFF', cockpit: '#C9D0E0', personality: "Effortlessly surfing invisible shifts." , beat: 'Chase him downwind — clouds stall when the wind goes aft.', archetype: 'shift', stats: { acceleration: 4, momentum: -5, handling: -4, upwind: 1, reach: 1, downwind: -5, pressure: 0, lightAir: 4, heavyAir: -3, memory: -1 } },
    { name: 'Tangle', creature: 'Common Octopus', hull: '#7A1FA2', spinnaker: '#00E676', spinnaker2: '#7A1FA2', sail: '#FFFFFF', cockpit: '#B8ACC9', personality: "Trap-setting master of dirty air." , beat: 'Dive downwind — the trap-setter unravels on the runs.', archetype: 'leech', stats: { acceleration: -1, momentum: 1, handling: -3, upwind: -2, reach: -1, downwind: -5, pressure: 5, lightAir: 1, heavyAir: -2, memory: 5 } },
    { name: 'Brine', creature: 'Florida Manatee', hull: '#A65A45', spinnaker: '#FFB4A2', spinnaker2: '#FFFFFF', spinnaker3: '#8FB8D8', sail: '#FFFFFF', cockpit: '#C3CCD2', personality: "Looks slow, impossible to pass." , beat: 'Break his rhythm at the marks — restarts are agony for a manatee.', archetype: 'freight', stats: { acceleration: -5, momentum: 3, handling: 3, upwind: 3, reach: -2, downwind: 4, pressure: -4, lightAir: -2, heavyAir: -4, memory: 1 } },
    { name: 'Razor', creature: 'Barracuda', hull: '#2D3142', spinnaker: '#EF233C', spinnaker2: '#2D3142', sail: '#FFFFFF', cockpit: '#5C5F6A', personality: "Surgical aggression at the worst moments." , beat: 'No weak stat — refuse the fight and race your own boat.', archetype: 'bully', stats: { acceleration: 0, momentum: 4, handling: 5, upwind: -1, reach: 0, downwind: -1, pressure: -1, lightAir: -2, heavyAir: 2, memory: 1 } },
    { name: 'Pebble', creature: 'Adelie Penguin', hull: '#1F1F1F', spinnaker: '#00B4D8', spinnaker2: '#FFFFFF', spinnaker3: '#1F1F1F', sail: '#FFFFFF', cockpit: '#C7CCD1', personality: "Precise and unshakable in traffic." , beat: 'Reach across her line — precision cannot fix a slow reach.', archetype: 'metronome', stats: { acceleration: -2, momentum: 5, handling: 3, upwind: 5, reach: -4, downwind: 4, pressure: -2, lightAir: -1, heavyAir: 4, memory: 5 } },
    { name: 'Saffron', creature: 'Lined Seahorse', hull: '#FFB000', spinnaker: '#7B2CBF', spinnaker2: '#FFB000', sail: '#FFFFFF', cockpit: '#CBBFA6', personality: "Graceful wildcard favoring wide tactics." , beat: 'She bets it all on the reaches — win the beats and it is over.', archetype: 'gambler', stats: { acceleration: -4, momentum: -2, handling: 3, upwind: -5, reach: 5, downwind: 0, pressure: 5, lightAir: 5, heavyAir: -5, memory: 0 } },
    { name: 'Bramble', creature: 'Sea Urchin', hull: '#2B2E4A', spinnaker: '#A78BFA', spinnaker2: '#FF9F1C', spinnaker3: '#FFFFFF', sail: '#FFFFFF', cockpit: '#7A7F9A', personality: "Spiky defender denying easy lanes." , beat: 'Stay out of reach — alone, the urchin barely moves.', archetype: 'bully', stats: { acceleration: -5, momentum: 3, handling: -4, upwind: 3, reach: -1, downwind: 1, pressure: -4, lightAir: 1, heavyAir: -1, memory: -5 } },
    { name: 'Mistral', creature: 'Common Swift', hull: '#A8DADC', spinnaker: '#E63946', spinnaker2: '#FFFFFF', spinnaker3: '#A8DADC', sail: '#FFFFFF', cockpit: '#C4CFD4', personality: "Constantly sniffing out pressure." , beat: 'Fast everywhere — beat the swift on shifts, not speed.', archetype: 'shift', stats: { acceleration: 5, momentum: 5, handling: 2, upwind: 0, reach: -1, downwind: 0, pressure: -1, lightAir: 3, heavyAir: 3, memory: 2 } },
    { name: 'Drift', creature: 'Sea Nettle', hull: '#FF70A6', spinnaker: '#9B6FE0', spinnaker2: '#FF70A6', sail: '#FFFFFF', cockpit: '#D6C9D9', personality: "Harmless-looking, slips through gaps." , beat: 'Every maneuver hurts him — force gybes and watch him wilt.', archetype: 'gambler', stats: { acceleration: -4, momentum: -5, handling: -5, upwind: -2, reach: -1, downwind: 4, pressure: 4, lightAir: 5, heavyAir: -5, memory: -5 } },
    { name: 'Anchor', creature: 'Sea Turtle', hull: '#96C47A', spinnaker: '#FFD016', spinnaker2: '#1F5C33', spinnaker3: '#FFFFFF', sail: '#FFFFFF', cockpit: '#B7C4B4', personality: "Conservative, resilient, brutally consistent." , beat: 'Own the beats — the turtle only wins races run downhill.', archetype: 'metronome', stats: { acceleration: 3, momentum: 5, handling: -2, upwind: -5, reach: 0, downwind: -2, pressure: -1, lightAir: -1, heavyAir: 2, memory: 5 } },
    { name: 'Zing', creature: 'Flying Squirrel', hull: '#9B5DE5', spinnaker: '#FEE440', spinnaker2: '#9B5DE5', sail: '#FFFFFF', cockpit: '#CFC7DC', personality: "Hyperactive chaos opportunist." , beat: 'Survive the launch — the beats bring him back to you.', archetype: 'rocket', stats: { acceleration: 4, momentum: 5, handling: 4, upwind: -3, reach: -4, downwind: -2, pressure: 1, lightAir: 4, heavyAir: -4, memory: 1 } },
    { name: 'Knot', creature: 'Chambered Nautilus', hull: '#C8553D', spinnaker: '#6FAF58', spinnaker2: '#F0E4C8', spinnaker3: '#C8553D', sail: '#FFFFFF', cockpit: '#C8B5A6', personality: "Cerebral planner playing long games." , beat: 'Sail into pressure — the nautilus cannot cash a gust.', archetype: 'leech', stats: { acceleration: -2, momentum: -3, handling: 0, upwind: -3, reach: 0, downwind: 1, pressure: -4, lightAir: -1, heavyAir: -2, memory: 3 } },
    { name: 'Flash', creature: 'Mackerel', hull: '#3A86FF', spinnaker: '#F5E050', spinnaker2: '#FFFFFF', sail: '#000000', cockpit: '#B4C2D6', personality: "Speed-first, consequences later." , beat: 'Send him upwind — the sprinter\'s compass only points down.', archetype: 'rocket', stats: { acceleration: 2, momentum: -1, handling: 5, upwind: -5, reach: -1, downwind: 2, pressure: -4, lightAir: 1, heavyAir: -1, memory: -2 } },
    { name: 'Pearl', creature: 'Pacific Oyster', hull: '#C7A6FF', spinnaker: '#2E2E2E', spinnaker2: '#FFFFFF', spinnaker3: '#C7A6FF', sail: '#FFFFFF', cockpit: '#CFCFD4', personality: "Quiet patience, strikes at perfect moments." , beat: 'Make her tack — every stop costs a fortune in pearls.', archetype: 'leech', stats: { acceleration: 4, momentum: -5, handling: -1, upwind: -5, reach: 4, downwind: 5, pressure: 4, lightAir: 1, heavyAir: -3, memory: -2 } },
    { name: 'Bluff', creature: 'Polar Bear', hull: '#FFFFFF', spinnaker: '#2E5FD0', spinnaker2: '#FFFFFF', sail: '#FFFFFF', cockpit: '#BFC6CC', personality: "Imposing calm daring mistakes." , beat: 'Just point higher — Bluff bluffs; the upwind legs call it.', archetype: 'freight', stats: { acceleration: 2, momentum: 4, handling: -3, upwind: -5, reach: 0, downwind: 1, pressure: -1, lightAir: -4, heavyAir: 5, memory: 3 } },
    { name: 'Regal', creature: 'Mute Swan', hull: '#FFFFFF', spinnaker: '#E10600', spinnaker2: '#FFFFFF', spinnaker3: '#1A1A1A', sail: '#000000', cockpit: '#C9CCD6', personality: "Elegant lane thief with ruthless timing." , beat: 'Race the runs — royalty will not hoist and hustle.', archetype: 'corner', stats: { acceleration: -1, momentum: 3, handling: 5, upwind: 0, reach: 4, downwind: -4, pressure: -2, lightAir: 2, heavyAir: -1, memory: 2 } },
    { name: 'Sunshine', creature: 'Mahi-Mahi', hull: '#FFEB3B', spinnaker: '#00E676', spinnaker2: '#FFEB3B', spinnaker3: '#FFFFFF', sail: '#FFFFFF', cockpit: '#BDB76B', personality: "Flashy speed attacking on reaches." , beat: 'Keep her in lulls and dirty air — no gusts, no shine.', archetype: 'rocket', stats: { acceleration: 1, momentum: -4, handling: 1, upwind: 4, reach: 0, downwind: -1, pressure: -4, lightAir: 1, heavyAir: 0, memory: -1 } },
    { name: 'Pulse', creature: 'Tree Frog', hull: '#00FF6A', spinnaker: '#7A00FF', spinnaker2: '#00FF6A', sail: '#FFFFFF', cockpit: '#C9CCD6', personality: "Sticky feet, sticky cover — impossible to shake loose." , beat: 'Break away off the wind — sticky feet, short hops.', archetype: 'leech', stats: { acceleration: -3, momentum: 2, handling: -1, upwind: -3, reach: -5, downwind: -5, pressure: 2, lightAir: 4, heavyAir: -4, memory: 0 } },
    { name: 'Splat', creature: 'Blobfish', hull: '#E7A6B4', spinnaker: '#6a1051', spinnaker2: '#E7A6B4', sail: '#FFFFFF', cockpit: '#CFC6CC', personality: "Looks doomed, but somehow always survives." , beat: 'Just race — his corner needs a miracle and a tailwind.', archetype: 'gambler', stats: { acceleration: -5, momentum: 0, handling: -3, upwind: 0, reach: -2, downwind: 0, pressure: 1, lightAir: -2, heavyAir: -5, memory: -3 } },
    { name: 'Dart', creature: 'Kingfisher', hull: '#00C2FF', spinnaker: '#FF9433', spinnaker2: '#FFFFFF', spinnaker3: '#F5A03C', sail: '#FFFFFF', cockpit: '#AEBFCC', personality: "pure speed, energetic, very competitive" , beat: 'Point high and turn often — darts only fly straight.', archetype: 'rocket', stats: { acceleration: 1, momentum: 4, handling: -3, upwind: -4, reach: 4, downwind: -2, pressure: 5, lightAir: 2, heavyAir: -1, memory: 3 } },
    { name: 'Roll', creature: 'Harbor Seal', hull: '#7D8597', spinnaker: '#FFD166', spinnaker2: '#FFFFFF', sail: '#FFFFFF', cockpit: '#C3CAD3', personality: "Playful feints hiding brutal positioning skills." , beat: 'Slow him leaving marks — perfect turns, painful exits.', archetype: 'corner', stats: { acceleration: -5, momentum: 4, handling: 5, upwind: -3, reach: 0, downwind: -3, pressure: 0, lightAir: 0, heavyAir: 2, memory: 3 } },
    { name: 'Spike', creature: 'Narwhal', hull: '#6B7FD7', spinnaker: '#FFFFFF', spinnaker2: '#6B7FD7', sail: '#000000', cockpit: '#C5CED6', personality: "Leads with the horn — makes his own right of way." , beat: 'Point high and stay clear of the horn — he cannot climb after you.', archetype: 'bully', stats: { acceleration: 1, momentum: -2, handling: 1, upwind: -5, reach: 2, downwind: 1, pressure: 3, lightAir: -2, heavyAir: 4, memory: 3 } },
    { name: 'Flicker', creature: 'Arctic Tern', hull: '#EE6C4D', spinnaker: '#E0FBFC', spinnaker2: '#EE6C4D', sail: '#000000', cockpit: '#C7CCD1', personality: "Constant repositioning, never predictable." , beat: 'Follow the fleet, not the tern — his corner rarely pays.', archetype: 'gambler', stats: { acceleration: 2, momentum: 3, handling: -2, upwind: -2, reach: 1, downwind: 0, pressure: -1, lightAir: 2, heavyAir: -1, memory: 4 } },
    { name: 'Croak', creature: 'American Bullfrog', hull: '#386641', spinnaker: '#A7C957', spinnaker2: '#FFFFFF', sail: '#FFFFFF', cockpit: '#BFC9B8', personality: "Patient swamp tactician who waits for the wind to die." , beat: 'Race him when it honks — the bullfrog only sings in a whisper.', archetype: 'shift', stats: { acceleration: 1, momentum: -3, handling: -2, upwind: 0, reach: -2, downwind: 0, pressure: -1, lightAir: 5, heavyAir: -5, memory: 2 } },
    { name: 'Snap', creature: 'Snapping Turtle', hull: '#4B5D23', spinnaker: '#ef3629', spinnaker2: '#000000', sail: '#000000', cockpit: '#B8B8A8', personality: "Grouchy, old salty sailor who likes to beat the young whippersnappers." , beat: 'Keep him turning — snappers lose their grip in maneuvers.', archetype: 'metronome', stats: { acceleration: -2, momentum: -4, handling: -4, upwind: 2, reach: 0, downwind: 1, pressure: 1, lightAir: -1, heavyAir: 3, memory: 3 } },
    { name: 'Rift', creature: 'Moray Eel', hull: '#d4ff07', spinnaker: '#FF61DF', spinnaker2: '#1A1A1A', sail: '#FFFFFF', cockpit: '#B7C4B4', personality: "Lurks quietly, strikes savagely at marks." , beat: 'Pull away on the runs — eels do not surf.', archetype: 'corner', stats: { acceleration: -1, momentum: -3, handling: 2, upwind: 2, reach: 3, downwind: -4, pressure: 2, lightAir: 1, heavyAir: -1, memory: 4 } },
    { name: 'Skerry', creature: 'Atlantic Puffin', hull: '#FF5400', spinnaker: '#1D3557', spinnaker2: '#FFFFFF', sail: '#FFFFFF', cockpit: '#C7CCD1', personality: "Fearless gap-threader thriving in traffic." , beat: 'Give him no gaps to thread — then climb away upwind.', archetype: 'bully', stats: { acceleration: -2, momentum: 1, handling: -1, upwind: -3, reach: 3, downwind: 2, pressure: -2, lightAir: 2, heavyAir: 2, memory: 4 } },
    { name: 'Crush', creature: 'Mantis Shrimp', hull: '#00F5D4', spinnaker: '#F15BB5', spinnaker2: '#00F5D4', sail: '#000000', cockpit: '#CFC7DC', personality: "Explosive reactions with devastating timing." , beat: 'Everything between corners is yours — especially the runs.', archetype: 'corner', stats: { acceleration: 4, momentum: -5, handling: 2, upwind: 3, reach: 2, downwind: -5, pressure: 2, lightAir: 2, heavyAir: -1, memory: 4 } },
    { name: 'Torrent', creature: 'Swordfish', hull: '#083fa6', spinnaker: '#FFFFFF', spinnaker2: '#2E6FD0', spinnaker3: '#D62828', sail: '#FFFFFF', cockpit: '#8D99AE', personality: "Straight-line dominance with brutal acceleration." , beat: 'Absorb the opening surge — the swordfish dulls by leg two.', archetype: 'rocket', stats: { acceleration: 5, momentum: -2, handling: 1, upwind: 1, reach: -1, downwind: -2, pressure: 2, lightAir: -3, heavyAir: 4, memory: 0 } },
    { name: 'Jester', creature: 'Clownfish', hull: '#ffa000', spinnaker: '#FFFFFF', spinnaker2: '#ffa000', sail: '#000000', cockpit: '#f4f4f4', personality: "Cheerful chaos masking shrewd cunning." , beat: 'Escape upwind — the joke is on him above the layline.', archetype: 'leech', stats: { acceleration: 1, momentum: 0, handling: 2, upwind: -3, reach: 0, downwind: 2, pressure: -1, lightAir: 4, heavyAir: -4, memory: 3 } },
    { name: 'Breeze', creature: 'Nudibranch', hull: '#000080', spinnaker: '#ff3fa7', spinnaker2: '#FFFFFF', sail: '#FFFFFF', cockpit: '#D6D6DC', personality: "Chill, stylish, always finds unexpected pressure." , beat: 'Crowd her at starts and marks — slow to build speed, easy to pin.', archetype: 'shift', stats: { acceleration: -4, momentum: 4, handling: -2, upwind: -3, reach: 4, downwind: 1, pressure: 5, lightAir: 4, heavyAir: -5, memory: -3 } },
    { name: 'Petal', creature: 'Roseate Spoonbill', hull: '#FF6FAE', spinnaker: '#FFFFFF', spinnaker2: '#FF6FAE', sail: '#FFFFFF', cockpit: '#e6e6e6', personality: "Elegant lane snatcher with impeccable timing." , beat: 'Win the beats — the spoonbill blooms only at the marks.', archetype: 'corner', stats: { acceleration: -3, momentum: 3, handling: 1, upwind: -5, reach: -1, downwind: 3, pressure: 4, lightAir: 3, heavyAir: -3, memory: 3 } },
    { name: 'Stomp', creature: 'Blue-Footed Booby', hull: '#00B4D8', spinnaker: '#F5F7FA', spinnaker2: '#FFFFFF', sail: '#FFFFFF', cockpit: '#C9CCD6', personality: "Clumsy confidence hiding fearless lane attacks." , beat: 'Refuse the brawl and outlast him — stomping bleeds speed.', archetype: 'bully', stats: { acceleration: 5, momentum: -3, handling: 4, upwind: 3, reach: 2, downwind: 0, pressure: 1, lightAir: 0, heavyAir: 1, memory: 0 } },
    { name: 'Crimson', creature: 'Red Snapper', hull: '#ed1515', spinnaker: '#2643E9', spinnaker2: '#FFFFFF', sail: '#FFFFFF', cockpit: '#CFCFD4', personality: "Calm, surgical tactician striking at perfect moments." , beat: 'Break away in a straight line — he only shines in puffs.', archetype: 'leech', stats: { acceleration: -1, momentum: -3, handling: 1, upwind: 0, reach: -3, downwind: -2, pressure: 2, lightAir: 0, heavyAir: 0, memory: 1 } },
    { name: 'Viper', creature: 'Green Tree Snake', hull: '#49c100', spinnaker: '#C4E63C', spinnaker2: '#1A1A1A', sail: '#FFFFFF', cockpit: '#C9CCD6', personality: "Coils around your wind and waits for the twitch." , beat: 'Slip the cover in open water — he fades on the long legs.', archetype: 'leech', stats: { acceleration: -3, momentum: -2, handling: -2, upwind: -5, reach: -1, downwind: -5, pressure: 3, lightAir: 2, heavyAir: -1, memory: 1 } },
    { name: 'Skitter', creature: 'Atlantic Mudskipper', hull: '#e33d28', spinnaker: '#15f121', spinnaker2: '#FFFFFF', sail: '#FFFFFF', cockpit: '#C9CCD6', personality: "Erratic scrambler who thrives where the water runs out." , beat: 'Wait for the breeze to fill — the mudskipper needs a drifter to matter.', archetype: 'gambler', stats: { acceleration: 1, momentum: -4, handling: -2, upwind: -1, reach: -3, downwind: -2, pressure: -3, lightAir: 4, heavyAir: -4, memory: 2 } },
    { name: 'Veil', creature: 'Vampire Squid', hull: '#7A1FA2', spinnaker: '#E10600', spinnaker2: '#1A1A1A', spinnaker3: '#FFFFFF', sail: '#FFFFFF', cockpit: '#C9CCD6', personality: "Calm, shadowy predator striking without warning." , beat: 'Force maneuvers — the cloak tears in every tack.', archetype: 'leech', stats: { acceleration: -1, momentum: -4, handling: -5, upwind: -1, reach: 3, downwind: -1, pressure: -4, lightAir: 2, heavyAir: -4, memory: -1 } },
    { name: 'Puff', creature: 'Mandarin Dragonet', hull: '#0032FF', spinnaker: '#F0A040', spinnaker2: '#1890FC', spinnaker3: '#62E517', sail: '#FFFFFF', cockpit: '#BFC8D6', personality: "Super chill vibes, effortless flow, always smiling." , beat: 'Attack downwind — the dragonet will not run with you.', archetype: 'freight', stats: { acceleration: 2, momentum: 4, handling: 1, upwind: 1, reach: 2, downwind: -3, pressure: 4, lightAir: 5, heavyAir: -3, memory: 2 } },
    { name: 'Lure', creature: 'Black Seadevil', hull: '#0B0F1A', spinnaker: '#6AFF3D', spinnaker2: '#0B0F1A', sail: '#F5F7FA', cockpit: '#2E3440', personality: "Patient darkness, sudden lethal strikes." , beat: 'Refuse the bait upwind — the runs are a free pass.', archetype: 'freight', stats: { acceleration: -4, momentum: 5, handling: 0, upwind: 3, reach: 5, downwind: -5, pressure: 5, lightAir: 3, heavyAir: -5, memory: 1 } },
    { name: 'Wiggle', creature: 'Axolotl', hull: '#FFFFFF', spinnaker: '#FF4FA3', spinnaker2: '#BDEFFF', sail: '#BDEFFF', cockpit: '#D1D7DB', personality: "Cute chaos, surprisingly competitive." , beat: 'Make him steer — wiggling is not turning.', archetype: 'gambler', stats: { acceleration: 2, momentum: 1, handling: -5, upwind: -3, reach: 3, downwind: 3, pressure: -3, lightAir: 4, heavyAir: -4, memory: -1 } },
    { name: 'Zeffir', creature: 'Herring Gull', hull: '#FFFFFF', spinnaker: '#FF7A00', spinnaker2: '#FFFFFF', sail: '#FFFFFF', cockpit: '#D1D7DB', personality: "Always lifted, always smiling." , beat: 'Hold him off downwind — gulls glide everywhere but there.', archetype: 'shift', stats: { acceleration: 4, momentum: 1, handling: -1, upwind: 1, reach: 2, downwind: -4, pressure: 2, lightAir: 1, heavyAir: 3, memory: 2 } },
    { name: 'Scoop', creature: 'Brown Pelican', hull: '#D8C6A3', spinnaker: '#5499DC', spinnaker2: '#FFFFFF', spinnaker3: '#D8C6A3', sail: '#FFFFFF', cockpit: '#e6e6e6', personality: "Big moves, surprisingly precise." , beat: 'Rush the starts and reaches — the pelican needs a runway.', archetype: 'metronome', stats: { acceleration: -4, momentum: -1, handling: 1, upwind: 4, reach: -4, downwind: -1, pressure: 2, lightAir: 0, heavyAir: 2, memory: 2 } },
    { name: 'Popper', creature: 'Pufferfish', hull: '#FFD84D', spinnaker: '#E10600', spinnaker2: '#FFD84D', sail: '#FFFFFF', cockpit: '#C9CCD6', personality: "Defensive chaos, punishes reckless pressure." , beat: 'Point higher and let him puff himself out.', archetype: 'bully', stats: { acceleration: -3, momentum: 0, handling: -2, upwind: -4, reach: 3, downwind: 1, pressure: 4, lightAir: 1, heavyAir: -2, memory: 0 } },
    { name: 'Frond', creature: 'Leafy Seadragon', hull: '#5FAF6E', spinnaker: '#C8E8B8', spinnaker2: '#5FAF6E', sail: '#F3FFF9', cockpit: '#BFCFC4', personality: "Graceful drifter, impossible to read." , beat: 'Pin him at the start — the seadragon blooms late, downwind.', archetype: 'shift', stats: { acceleration: -4, momentum: -2, handling: -3, upwind: -1, reach: 1, downwind: 5, pressure: 0, lightAir: 5, heavyAir: -5, memory: 0 } },
    { name: 'Bulkhead', creature: 'Elephant Seal', hull: '#6B7280', spinnaker: '#FF7A00', spinnaker2: '#1A1A1A', spinnaker3: '#FFFFFF', sail: '#FFFFFF', cockpit: '#C9CCD6', personality: "A wall of calm — unbothered, unhurried, unmoved." , beat: 'Hoist and go — the bulkhead sinks on every run.', archetype: 'metronome', stats: { acceleration: -3, momentum: -2, handling: 2, upwind: 3, reach: -1, downwind: -5, pressure: 5, lightAir: -5, heavyAir: 5, memory: 2 } },
    { name: 'Slipstream', creature: 'Sockeye Salmon', hull: '#B6BCC6', spinnaker: '#4FBF3C', spinnaker2: '#FFFFFF', spinnaker3: '#E94B4B', sail: '#FFFFFF', cockpit: '#41c617', personality: "Relentless endurance, explosive late surges." , beat: 'Deny the tow upwind, then leave — salmon cannot run downstream.', archetype: 'freight', stats: { acceleration: 5, momentum: 3, handling: 1, upwind: 1, reach: -3, downwind: -5, pressure: -1, lightAir: 0, heavyAir: 2, memory: 5 } },
    { name: 'Blaze', creature: 'Mako Shark', hull: '#1F3C5B', spinnaker: '#FFFFFF', spinnaker2: '#1F3C5B', spinnaker3: '#00A8E8', sail: '#FFFFFF', cockpit: '#C9CCD6', personality: "Blisteringly fast attacker forcing races into constant reaction mode." , beat: 'Skip the fight, win the runs — makos idle downwind.', archetype: 'bully', stats: { acceleration: -3, momentum: -2, handling: 2, upwind: 2, reach: 3, downwind: -4, pressure: 2, lightAir: -3, heavyAir: 3, memory: 1 } },
    { name: 'Cruz', creature: 'California Newt', hull: '#F08A1E', spinnaker: '#2E3440', spinnaker2: '#F0E0B0', spinnaker3: '#E06A00', sail: '#FFFFFF', cockpit: '#CFC3A8', personality: "Unhurried, unbothered, and never once out of position.", beat: 'Nothing to exploit — get ahead early, because he has no burst to take it back.', archetype: 'metronome', stats: { acceleration: 2, momentum: 2, handling: 2, upwind: 2, reach: 2, downwind: 2, pressure: 2, lightAir: 1, heavyAir: 1, memory: 3 } },
    { name: 'Prism', creature: 'Maxima Clam', hull: '#2A1070', spinnaker: '#00D9CB', spinnaker2: '#A93FE8', spinnaker3: '#F0F4FF', sail: '#FFFFFF', cockpit: '#BFC6DB', personality: "A slow strange jewel that arrives faster than it has any right to.", beat: 'Bury him at the start — a clam that has to accelerate is a clam you have beaten.', archetype: 'freight', stats: { acceleration: -4, momentum: 5, handling: -3, upwind: 0, reach: 3, downwind: 2, pressure: 3, lightAir: -1, heavyAir: 2, memory: -2 } },
    { name: 'Ember', creature: 'Firefish', hull: '#A855E8', spinnaker: '#F5A03C', spinnaker2: '#FFFFFF', spinnaker3: '#7A3FD4', sail: '#FFFFFF', cockpit: '#C9BFD6', personality: "Burns hot off the line and dares the fleet to keep up.", beat: 'Make the race long — the firefish spends everything in the first minute.', archetype: 'rocket', stats: { acceleration: 5, momentum: -4, handling: 2, upwind: -2, reach: 2, downwind: 0, pressure: 1, lightAir: 2, heavyAir: -3, memory: 0 } },
    { name: 'Torpedo', creature: 'Northern Pike', hull: '#7A8C3C', spinnaker: '#D8402F', spinnaker2: '#F0E0A0', spinnaker3: '#4A5A28', sail: '#FFFFFF', cockpit: '#C4C4A0', personality: "Learns the water once, then hunts it from memory.", beat: 'Take him somewhere new — the pike is only lethal on water he already knows.', archetype: 'freight', stats: { acceleration: 3, momentum: 4, handling: -4, upwind: -1, reach: 4, downwind: 1, pressure: 0, lightAir: -1, heavyAir: 2, memory: 4 } },
    { name: 'Flaunt', creature: 'Anemone Shrimp', hull: '#F58BA0', spinnaker: '#00C2E0', spinnaker2: '#FF3B5C', spinnaker3: '#FFFFFF', sail: '#FFFFFF', cockpit: '#E8D4DA', personality: "Dazzling, theatrical, and quietly stealing your lane the whole time.", beat: 'Sail your own race — every trick she has costs her when the breeze gets up.', archetype: 'gambler', stats: { acceleration: 5, momentum: -4, handling: 5, upwind: -3, reach: 2, downwind: 0, pressure: 2, lightAir: 3, heavyAir: -4, memory: 1 } },
    { name: 'Piper', creature: 'Sanderling', hull: '#E8DCC0', spinnaker: '#2E9BF0', spinnaker2: '#FFFFFF', sail: '#FFFFFF', cockpit: '#C9CCD6', personality: "Threads gaps at the mark that nobody else even sees.", beat: 'Take her downwind and stretch — precision is worth nothing on an empty run.', archetype: 'corner', stats: { acceleration: 3, momentum: -4, handling: 5, upwind: 1, reach: 0, downwind: -3, pressure: 2, lightAir: 2, heavyAir: -2, memory: 3 } },
    { name: 'Stripes', creature: 'Tiger Shark', hull: '#8A6A3A', spinnaker: '#F0C82E', spinnaker2: '#2B2B2B', sail: '#000000', cockpit: '#B8AE96', personality: "Eats mistakes. Sail clean and he has nothing to work with.", beat: 'Give him no errors — the tiger has no plan of his own.', archetype: 'leech', stats: { acceleration: 1, momentum: 4, handling: 0, upwind: 1, reach: 0, downwind: 1, pressure: -2, lightAir: -2, heavyAir: 3, memory: 3 } },
    { name: 'Anvil', creature: 'Hammerhead Shark', hull: '#6E7A85', spinnaker: '#F5851F', spinnaker2: '#1C709A', sail: '#FFFFFF', cockpit: '#C2C8CE', personality: "Wide, heavy and utterly immovable once he owns the lane.", beat: 'Beat him off the line — the hammer needs a lane before it is worth anything.', archetype: 'bully', stats: { acceleration: -4, momentum: 3, handling: -3, upwind: 4, reach: 2, downwind: 1, pressure: -3, lightAir: -3, heavyAir: 4, memory: 1 } },
    { name: 'Paddle', creature: 'Mallard Duck', hull: '#2FAE5C', spinnaker: '#F58A00', spinnaker2: '#6B4A2A', sail: '#FFFFFF', cockpit: '#C9CCD6', personality: "Taught half the fleet to sail, and still beats most of them.", beat: 'Wait for it to blow — he learned on a pond and never really left it.', archetype: 'metronome', stats: { acceleration: 1, momentum: 1, handling: 1, upwind: 0, reach: -1, downwind: -1, pressure: -2, lightAir: 3, heavyAir: -2, memory: 2 } },
    { name: 'Etienne', creature: 'Red Swamp Crayfish', hull: '#DE4F3C', spinnaker: '#50B090', spinnaker2: '#FFFFFF', sail: '#FFFFFF', cockpit: '#C6B49A', personality: "Scrappy bayou grinder who would rather hold a lane than win one.", beat: 'Race him in open water — the crawdad only understands a narrow channel.', archetype: 'corner', stats: { acceleration: -1, momentum: 3, handling: 1, upwind: 1, reach: -2, downwind: -2, pressure: -1, lightAir: 4, heavyAir: -3, memory: 2 } },
    { name: 'Frenzy', creature: 'Red-Bellied Piranha', hull: '#CE3B3B', spinnaker: '#1E7A4A', spinnaker2: '#FFFFFF', sail: '#000000', cockpit: '#A8B4B8', personality: "Feeds on a messy start and gets bored in clean air.", beat: 'Keep it tidy — with nothing to bite, the piranha simply drifts.', archetype: 'gambler', stats: { acceleration: 3, momentum: -3, handling: -1, upwind: -4, reach: 0, downwind: 0, pressure: 0, lightAir: 1, heavyAir: -1, memory: -1 } },
    { name: 'Tiny', creature: 'Antarctic Krill', hull: '#F26E6E', spinnaker: '#3D6FC4', spinnaker2: '#FFFFFF', sail: '#FFFFFF', cockpit: '#DCC6C6', personality: "All twitch and no mass — turns like nothing else afloat.", beat: 'Just point at the mark — anything above a breeze blows the krill away.', archetype: 'rocket', stats: { acceleration: 5, momentum: -5, handling: 4, upwind: -3, reach: -1, downwind: -2, pressure: -1, lightAir: 5, heavyAir: -5, memory: -3 } },
    { name: 'Grip', creature: 'Acorn Barnacle', hull: '#8A8D93', spinnaker: '#2E7D32', spinnaker2: '#FFFFFF', sail: '#FFFFFF', cockpit: '#C9CCD6', personality: "Immovable. Wins the one metre he is standing on and nothing else.", beat: 'Sail around him — he cannot follow, and he was never going to.', archetype: 'bully', stats: { acceleration: -5, momentum: 5, handling: -5, upwind: -5, reach: -3, downwind: -4, pressure: 5, lightAir: -5, heavyAir: 5, memory: 0 } },
    { name: 'Splash', creature: 'Hippopotamus', hull: '#6F7782', spinnaker: '#EE3B2B', spinnaker2: '#FFFFFF', sail: '#FFFFFF', cockpit: '#C9CCD6', personality: "Enormous, delighted, and genuinely dangerous with the kite up.", beat: 'Never let him start a run in front — everywhere else he is a barge.', archetype: 'freight', stats: { acceleration: -4, momentum: 5, handling: -5, upwind: -4, reach: -2, downwind: 4, pressure: -3, lightAir: -4, heavyAir: 4, memory: 1 } },
    { name: 'Dozer', creature: 'Nurse Shark', hull: '#B0824F', spinnaker: '#7DE2C3', spinnaker2: '#FFFFFF', sail: '#FFFFFF', cockpit: '#C6BBA6', personality: "Sleeps through the start and wakes up somewhere near your transom.", beat: 'Put a lap on him early — the nurse shark needs the whole race to get going.', archetype: 'freight', stats: { acceleration: -5, momentum: 5, handling: -4, upwind: 0, reach: -1, downwind: 1, pressure: -4, lightAir: -2, heavyAir: 3, memory: 2 } },
    { name: 'Muninn', creature: 'Common Raven', hull: '#1B2038', spinnaker: '#12A0FF', spinnaker2: '#FFFFFF', spinnaker3: '#6B4FD6', sail: '#101014', cockpit: '#C3C7D2', personality: "Remembers every shift he has ever seen, and sails you with it.", beat: 'Run him downwind — memory is worth nothing on water he has not learned.', archetype: 'shift', traits: { windFast: 1.75 }, stats: { acceleration: 2, momentum: -3, handling: 4, upwind: 3, reach: 3, downwind: -2, pressure: 5, lightAir: 2, heavyAir: -1, memory: 5 } },

    // ── The hundred. Eighteen added Aug 1 2026; colours are measured from each
    // shipped portrait so the boat matches the face. See art/new-character-prompt.md.
    { name: 'Talon', creature: 'Bald Eagle', hull: '#0A39A1', spinnaker: '#8A4A1D', spinnaker2: '#F2F2F0', sail: '#FFFFFF', cockpit: '#C3C7D2', personality: "Commits the instant he sees an opening, and never looks twice.", beat: 'Take him downwind — all that height is worth nothing with the wind behind.', archetype: 'rocket', stats: { acceleration: 5, momentum: -4, handling: 3, upwind: 5, reach: 4, downwind: -3, pressure: 3, lightAir: 1, heavyAir: 1, memory: 0 } },
    { name: 'Latch', creature: 'Remora', hull: '#C40A60', spinnaker: '#029E99', spinnaker2: '#F0EDE4', sail: '#FFFFFF', cockpit: '#BFC4CC', personality: "Finds the fastest boat in the fleet and simply stays there.", beat: 'Break the tow — nobody has ever seen him accelerate on his own.', archetype: 'leech', stats: { acceleration: -3, momentum: 5, handling: 1, upwind: 1, reach: 2, downwind: -1, pressure: 5, lightAir: 0, heavyAir: -2, memory: 2 } },
    { name: 'Skip', creature: 'Green Basilisk', hull: '#0C3FC0', spinnaker: '#3F8B0A', spinnaker2: '#F5E14A', spinnaker3: '#0C3FC0', sail: '#FFFFFF', cockpit: '#C7CBD4', personality: "Leaves before the gun and asks questions afterwards.", beat: 'Make it a long leg — he spends everything in ten seconds and has nothing left to carry.', archetype: 'rocket', stats: { acceleration: 5, momentum: -5, handling: 0, upwind: -4, reach: 3, downwind: -2, pressure: 0, lightAir: 2, heavyAir: 0, memory: -2 } },
    { name: 'Sable', creature: 'Great Cormorant', hull: '#17CCC1', spinnaker: '#AF25CF', spinnaker2: '#1E2430', sail: '#101014', cockpit: '#C9CCD6', personality: "Rounds every mark as though it had been measured beforehand.", beat: 'Crowd her — she sails a clean lane or none at all, and dirty air undoes her.', archetype: 'corner', stats: { acceleration: 1, momentum: 0, handling: 5, upwind: 0, reach: 1, downwind: -1, pressure: -3, lightAir: -1, heavyAir: 2, memory: 3 } },
    { name: 'Seam', creature: 'Rainbow Trout', hull: '#009078', spinnaker: '#F00030', spinnaker2: '#F2EAD2', sail: '#FFFFFF', cockpit: '#C5C9D1', personality: "Sees the shift a beat before it arrives, and takes it every time.", beat: 'Wait for it to blow — she reads the light stuff beautifully and drowns above sixteen knots.', archetype: 'shift', stats: { acceleration: 1, momentum: -4, handling: 3, upwind: 4, reach: 1, downwind: -3, pressure: 3, lightAir: 4, heavyAir: -4, memory: 1 } },
    { name: 'Snag', creature: 'Hellbender', hull: '#78CE33', spinnaker: '#C8912A', spinnaker2: '#2B2118', sail: '#101014', cockpit: '#BCC0C7', personality: "Has been in this river longer than the river has.", beat: 'Force him to turn — a tacking duel is the one thing he cannot answer.', archetype: 'metronome', stats: { acceleration: -4, momentum: 5, handling: -4, upwind: -3, reach: 3, downwind: -2, pressure: 2, lightAir: -1, heavyAir: 3, memory: 5 } },
    { name: 'Lunker', creature: 'Largemouth Bass', hull: '#4520A6', spinnaker: '#A0E203', spinnaker2: '#12121A', sail: '#FFFFFF', cockpit: '#C2C6CF', personality: "Picks a side of the course and dares you to disagree.", beat: 'Wait for a light day — he needs pressure to move, and he cannot turn when it arrives.', archetype: 'gambler', stats: { acceleration: -4, momentum: 2, handling: -3, upwind: -1, reach: -5, downwind: 0, pressure: 4, lightAir: -3, heavyAir: 3, memory: -4 } },
    { name: 'Flare', creature: 'Siamese Fighting Fish', hull: '#9444C0', spinnaker: '#1B8D84', spinnaker2: '#F0143C', sail: '#FFFFFF', cockpit: '#CBCFD8', personality: "Would rather win the argument than the race.", beat: 'Let him pick the fight, then leave downwind — that is exactly where he is slowest.', archetype: 'bully', stats: { acceleration: 4, momentum: -3, handling: 4, upwind: -3, reach: -4, downwind: -3, pressure: 1, lightAir: 2, heavyAir: 1, memory: -3 } },
    { name: 'Spar', creature: 'Blue Marlin', hull: '#326EC6', spinnaker: '#FCC20E', spinnaker2: '#EDF2F5', spinnaker3: '#12306B', sail: '#FFFFFF', cockpit: '#C6CAD3', personality: "Arrives at speed and expects the water to be clear.", beat: 'Attack at every mark — he rounds wide and cannot turn back inside you.', archetype: 'freight', stats: { acceleration: -3, momentum: 5, handling: -4, upwind: 2, reach: 5, downwind: 1, pressure: -1, lightAir: -2, heavyAir: 3, memory: 0 } },
    { name: 'Bloom', creature: 'Portuguese Man-of-War', hull: '#9FDC4A', spinnaker: '#EA7EFA', spinnaker2: '#3A2E5C', sail: '#FFFFFF', cockpit: '#CDD1D9', personality: "Has no rudder, no plan, and an uncanny amount of luck.", beat: 'Put a beat in front of her — she goes where the wind goes and cannot fight upwind.', archetype: 'gambler', stats: { acceleration: 2, momentum: 4, handling: -5, upwind: -3, reach: -4, downwind: -3, pressure: -1, lightAir: -3, heavyAir: 5, memory: -4 } },
    { name: 'Needle', creature: 'Gharial', hull: '#4C269C', spinnaker: '#DEEA49', spinnaker2: '#1A1A22', sail: '#FFFFFF', cockpit: '#C4C8D1', personality: "Threads gaps that were not there a moment earlier.", beat: 'Take him downwind — the precision that wins him marks is worth nothing on a run.', archetype: 'corner', stats: { acceleration: -1, momentum: -2, handling: 5, upwind: 3, reach: 1, downwind: -3, pressure: -1, lightAir: 2, heavyAir: 0, memory: 4 } },
    { name: 'Sovereign', creature: 'Napoleon Wrasse', hull: '#80D81B', spinnaker: '#E82393', spinnaker2: '#0E5C55', spinnaker3: '#F2F0E6', sail: '#FFFFFF', cockpit: '#C8CCD5', personality: "Treats the racecourse as a formality he has already won.", beat: 'Sail on his wind — grandeur does not survive being covered.', archetype: 'corner', stats: { acceleration: -3, momentum: 3, handling: 3, upwind: 4, reach: 4, downwind: -1, pressure: -4, lightAir: -1, heavyAir: 3, memory: 2 } },
    { name: 'Lateen', creature: 'By-the-wind Sailor', hull: '#D1DE09', spinnaker: '#16389A', spinnaker2: '#E8EEF5', sail: '#FFFFFF', cockpit: '#C0C4CD', personality: "Sets one sail, forever, and lets the day decide the rest.", beat: 'Send her upwind — a sail she cannot trim is no use against the breeze.', archetype: 'shift', stats: { acceleration: -4, momentum: -3, handling: -5, upwind: -4, reach: 4, downwind: 0, pressure: 5, lightAir: 2, heavyAir: -3, memory: -4 } },
    { name: 'Ribbon', creature: 'Yellow-lipped Sea Krait', hull: '#ADDA16', spinnaker: '#0B5EC0', spinnaker2: '#F5E23A', spinnaker3: '#14202E', sail: '#101014', cockpit: '#C1C5CE', personality: "Slides through the fleet without appearing to hurry.", beat: 'Take her air — she needs a clean lane and will not fight you for one.', archetype: 'corner', stats: { acceleration: 4, momentum: 1, handling: 4, upwind: 1, reach: 1, downwind: -2, pressure: -3, lightAir: 4, heavyAir: -3, memory: 1 } },
    { name: 'Plunge', creature: 'Northern Gannet', hull: '#1643AB', spinnaker: '#F9C915', spinnaker2: '#20242E', spinnaker3: '#F7F4E8', sail: '#FFFFFF', cockpit: '#C9CDD6', personality: "Picks a lane, folds, and commits — there is no second thought.", beat: 'Race him in a drifter — he needs wind to throw himself at, and dies without it.', archetype: 'rocket', stats: { acceleration: 5, momentum: -1, handling: -5, upwind: -3, reach: 0, downwind: -1, pressure: 2, lightAir: -4, heavyAir: 4, memory: 0 } },
    { name: 'Riffle', creature: 'American Dipper', hull: '#2A71B5', spinnaker: '#CFD213', spinnaker2: '#5E646B', sail: '#FFFFFF', cockpit: '#BEC2CB', personality: "Never stops moving, and never stops being right about the wind.", beat: 'Wait for a windy day — she is quick and clever until it blows, then she is just small.', archetype: 'shift', stats: { acceleration: 3, momentum: -3, handling: 4, upwind: -2, reach: -2, downwind: -2, pressure: 3, lightAir: 4, heavyAir: -3, memory: -3 } },
    { name: 'Chisel', creature: 'Humpback Chub', hull: '#32AD78', spinnaker: '#571A05', spinnaker2: '#E0CE93', sail: '#FFFFFF', cockpit: '#BDC1C9', personality: "Has one speed, and has never needed a second.", beat: 'Make him manoeuvre — he has no way of finding that speed again.', archetype: 'freight', stats: { acceleration: -4, momentum: 5, handling: -4, upwind: 0, reach: 3, downwind: 0, pressure: 3, lightAir: -3, heavyAir: 4, memory: 1 } },
    { name: 'Chroma', creature: 'Cuttlefish', hull: '#0AA79C', spinnaker: '#952FAC', spinnaker2: '#E8C77A', sail: '#FFFFFF', cockpit: '#C7CBD3', personality: "Reads the whole course, changes her mind, and is usually right.", beat: 'Push her into heavy air — the thinking stops working above sixteen knots.', archetype: 'shift', stats: { acceleration: 0, momentum: 0, handling: 3, upwind: -1, reach: 1, downwind: 1, pressure: 4, lightAir: 5, heavyAir: -4, memory: -5 } },
];
